### ISSUE TITLE
Unable to log in 

### ISSUE THREAD

**Issue by rposn** [opencdms/Climsoft#178]
I have seen that the alpha version of Climsoft is ready for testing. I am willing to test it, but I am not able to log in. The MySQL database has been succesfully installed, but when I enter my credentials (with "root" as username) a "Login failure" window pops-up (see screenshot below).
However, in previous stages of Climsoft, I was able to connect to the database (e.g. commit 8ea038b440134dab74275f9969c5a28bab791c7f). Is there something that I am missing? 
Is the mysql_climsoft_db_v4 still the database to use?
Thanks in advance and best regards!
![screenshot1](https://cloud.githubusercontent.com/assets/12081199/13594086/bd835104-e501-11e5-94fd-98d077d0d023.PNG)

**Comment by mhabimana** [comment]
Thanks Very much for your e-mail,
You are right,the Alpha is out and the database has changed,now we are using mariadb_climsoft_db_v4 configured at  port: 3308.So you will need to change the database.The latest changes will be pushed to GitHub very soon.Hope this will help.
Marcellin

**Comment by mhabimana** [comment]
Dear Raphael,
This is the new configuration of the database (config.inf),After synchronization you should get the latest copy of the climsoft version 4 on GitHub which has the new database configuration below :server=127.0.0.1;database=mariadb_climsoft_db_v4;port=3308; instead  of : server=127.0.0.1;database=mysql_climsoft_db_v4;port=3306;
Many thanks

**Comment by rposn** [comment]
Dear Marcellin,
Thanks for your quick answer. When I installed MariaDB I had to give a port number different from the default one (3306). At that time I chose 3307 as port, which seems to be the problem here. Since Climsoft was expecting port = 3308, it was not able to connect to the Maria database. I have changed the port number in the “config.inf” file to be 3307 and now I am able to log in!
Thank you very much!
Best regards,
Rafael

Von: Marcellin [mailto:notifications@github.com]
Gesendet: 08 March 2016 09:17
An: opencdms/Climsoft
Cc: rposn
Betreff: Re: [Climsoft] Unable to log in (#178)


Dear Raphael,
This is the new configuration of the database (config.inf),After synchronization you should get the latest copy of the climsoft version 4 on GitHub which has the new database configuration below :server=127.0.0.1;database=mariadb_climsoft_db_v4;port=3308; instead of : server=127.0.0.1;database=mysql_climsoft_db_v4;port=3306;
Many thanks

**Comment by mhabimana** [comment]
Thanks to hear that.However,the latest changes are not yet on the GitHub but will be pushed there very soon,will send you the link to the alpha setup as well very soon.
Thanks
