### ISSUE TITLE
Remove old message alert boxes

### ISSUE THREAD

**Issue by isedwards** [opencdms/Climsoft#181]
In metadata management, clicking anywhere in the area shown hatched in red causes a message box to be displayed with the message "Station"

Also, on any tab, clicking in the area shown hatched in blue causes a message box to be displayed containing an integer between 0 and 8.

![metadata_hatched](https://cloud.githubusercontent.com/assets/2097922/20215712/1029aa96-a80e-11e6-8e03-f958a91c4d8e.png)

**Comment by mhabimana** [comment]
Thanks,
You are right,I can see message boxes displayed exactly as you said.

**Comment by isedwards** [comment]
Fixed via discussion https://github.com/opencdms/Climsoft/pull/182
