### ISSUE TITLE
Record selection in Metadata Management

### ISSUE THREAD

**Issue by isedwards** [opencdms/Climsoft#183]
When viewing/editing metadata records, if you go to the final record it is currently then possible to keep going (the image below shows record 68 of 66).

The data shown to the user is not always the data corresponding to the record number shown in the scroll bar.

![metadata_1](https://cloud.githubusercontent.com/assets/2097922/20345732/6a308952-abf0-11e6-821e-37a400372d54.png)

The record count can also go out of sync when performing other operations (e.g. record 1 of 0).

![metadata_2](https://cloud.githubusercontent.com/assets/2097922/20345733/6a331596-abf0-11e6-9072-9d0edc8e32ae.png)

**Comment by mhabimana** [comment]
Dear Ian,Samuel,
The first observation is true on  climsoftV4 running on my PC,i.e: you can exceed the number of records and add additional 2 numbers (Eg: 281of 279).
![image](https://cloud.githubusercontent.com/assets/10340170/20346995/115bd9a6-ac10-11e6-9f8d-42fa84f86c2e.png)
Regards,
Marcellin

**Comment by isedwards** [comment]
@smachua has fixed this issue on the latest branch (not yet uploaded)
