### ISSUE TITLE
Updating licence information

### ISSUE THREAD

**Issue by isedwards** [opencdms/Climsoft#197]
The vb source code files in the Climsoft project contain a licence notice at the top of the file, e.g. [formElement.vb#L1-L15](https://github.com/opencdms/Climsoft/blob/master/ClimsoftVer4/ClimsoftVer4/formElement.vb#L1-L15)

This is missing from some of the files:
- [ ] Identify which vb files are missing the licence information
- [ ] Update these files
- [ ] Decide whether to update all vb files to change `Copyright (C) 2015` to `Copyright (C) 2017`

**Comment by tmundoga** [comment]
I have updated all the forms now ready for review

**Comment by mhabimana** [comment]
@tmundoga - Well done and noted. @isedwards will be back to you.

**Comment by mhabimana** [comment]
@tmundoga - I moved your task at another level (Issue Ready for Review),once approved ,I will move it to the final level (issue completed).
