### ISSUE TITLE
Contribution on Inventory

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#202]
Reports of data availability in the system (multiple stations, single station, etc.) in different formats (spreadsheet,text and Graphic).This area needs further contributions to make sure detailed and meaningful reports information can be produced from the data in the database. Contribution to this area of development will be highly appreciated.

**Comment by isedwards** [comment]
I think we should implement this as soon as possible

**Comment by vralenkoane** [comment]
Find below my suggested approach to Data Inventory.

The system provides details of missing data by

    Show of missing days in a month over all stations per element, the display is graphical and also provides an option to download the missing data in text format.
    Show of missing days in a year per station per element, the display is graphical and also provides an option to download the missing data in text format. Sample file infor & graph
    Show of missing days over all stations per element and and provides an option to download the data in text format.
    Optional: full db view as per the attached file. However, the description needs to be changed, that was meant for LMS.

​​Please note that on the graph is based on total count of number of days that are missing while the download​ data provide true reflection of missing days.

[MOS station Data Analysis.pdf](https://github.com/opencdms/Climsoft/files/1070784/MOS.station.Data.Analysis.pdf)
![inventory output](https://user-images.githubusercontent.com/15684269/27073251-7b930422-5023-11e7-91d2-ad2aecefa7d8.png)

**Comment by mhabimana** [comment]
@vralenkoane - Well done and noted. This is a new way of working or communicating. Other contributors/Developers will be able to comment on your post and not replying via email. For any correspondance/progress/etc. on this task,please use this plate form and not your email. Note that this issue number is opened and will be closed when you have done with the task.

**Comment by vralenkoane** [comment]
Can i start coding?

**Comment by mhabimana** [comment]
Sure,please go ahead.

**Comment by mhabimana** [comment]
@smachua,@isedwards - Do you have any suggestion to Victor?

**Comment by vralenkoane** [comment]
Lets hear a comment from the lead developers.

**Comment by mhabimana** [comment]
@vralenkoane - Are you able to receive notifications of the discussion in your email box?(e.g:the discussion we are doing should be received in your email box if the "Watching"button is ticked as shown below:
![image](https://user-images.githubusercontent.com/10340170/27074159-f362234c-502e-11e7-8fe6-e9e3e948d721.png)

**Comment by vralenkoane** [comment]
I have registered with another email and i can not receive emails on that account while connected to office internet due to firewall policy in place. i will confirm later

**Comment by mhabimana** [comment]
@vralenkoane -Thanks well noted.

**Comment by mhabimana** [comment]
@vralenkoane - I suggest you go to project/code development and move your task to the next level (drag and drop your task) to In Progress since you are going to embark on this task:
![image](https://user-images.githubusercontent.com/10340170/27075108-ad5574c8-5031-11e7-85c3-df5f2526bc34.png)

**Comment by vralenkoane** [comment]
how do i change status ?

**Comment by mhabimana** [comment]
@vralenkoane - Just drag and drop your task (From not started to in progress.

**Comment by isedwards** [comment]
@vralenkoane - it looks like only the lead developers can move the issues into other columns. The lead developer group is currently smachua, mhabimana and myself.

The difference is that the lead developers have write access to every part of the repository, whereas for everyone else it should be limited to individual branches initially (we're still testing this).

@mhabimana could you drag this across for Victor?

**Comment by mhabimana** [comment]
@isedwards -Well noted

**Comment by isedwards** [comment]
It would be good to approach this as two distinctly separate parts:
1. New code to create inventory plots for data extracted from the database
2. Modify the existing Climsoft code so that users can select the required data for the plot using the `Data Selection` form (accessed under `Climate Products` > `Inventory`).

Since the outputs will be created entirely using VB.NET I would suggest that Victor's work is included in Climsoft version 4.0, whereas some of the other work we are doing may be saved for a later version. Does this sound okay to you @smachua?

**Comment by vralenkoane** [comment]
I am lost. Please explain

**Comment by isedwards** [comment]
With fairly large pieces of work, I suggest breaking them down into a number of smaller pieces...

In this case, the first piece of work could be submitting a change that:
a) Adds a new form to the project with a chart component and the methods for updating the chart with the data
b) Demonstrate adding data from the Climsoft database to the chart (but the user would not be able to select what data is chosen, this would be fixed)

The first change would not:
a) Update the existing Data Selection code to allow the user to choose what data is displayed

Advantages
- We gain a useful (small) addition to the software very quickly, even if initially it does not solve the entire problem
- It lets other people see your solution much earlier and we can comment on progress so far
- If you stopped working on this issue then someone else could more easily pick up where you left off
- Sometimes it may end up making sense for someone else to do one of the other parts and then for you to review that it works well with your new code
- In this particular case, breaking the task into two parts would guarantee that your first submission is alongside the current code (but not actually modifying any of the current code yet) this may help us plan how the second part happens and avoid merge conflicts if two people are working on the same section of code by that time.

But, in this case there's no need to break if down if you don't want to.

**Comment by smachua** [comment]
The suggested contributions by Victor are impressive. I agree with Ian that this development can be implemented in version 4.0 and especially if it can be completed in June or early July. To start with, Victor can give us a design of his proposed interface for input requirements then we can give comments and suggestions before starting the coding. The design may be in a picture form just like the output images he has provided. When the designs are accepted then I can suggest the suitable area(s) of Climsoft project where the code modifications and additions can be done. That way I think the code integration will be smooth with minimal conflicts while merging. That is my thinking.

**Comment by vralenkoane** [comment]
Apologies for late response, I am recovering from flue. My implementation strategy is that at the database level, i will have a table that holds missing data and procedure that finds missing days per station per element. The procedure will clear the contents of the missing table before inserting records each time before it runs. The application will be calling the procedure and so to refresh the data.

**Comment by vralenkoane** [comment]
i however don't fully understand 'Design'

**Comment by mhabimana** [comment]
@vralenkoane - Well noted

**Comment by mhabimana** [comment]
@vralenkoane - I think the design here means the design view of the interface and not the code view.

**Comment by vralenkoane** [comment]
I will draw it and upload

**Comment by smachua** [comment]
The kind of design I was  simple graphics indicate how the input for the inventory processing will be provided. The input include stations selection, elements and the period (start yr, end yr, months etc). If found appropriate then the designs can be implemented as VB.Net forms.
On the other hand  you can use the already implemented products input interface shown below. If you're comfortable with that then you don't have to make any other design. Let me know so that I can direct you from where you can start putting your code.

![image](https://user-images.githubusercontent.com/12034121/27384283-073d25e2-5697-11e7-9166-521d8443220b.png)

**Comment by vralenkoane** [comment]
This is what i had in mind.
![capture](https://user-images.githubusercontent.com/15684269/27594057-1c5984b8-5b59-11e7-9eb0-949660e61c7a.JPG)

**Comment by vralenkoane** [comment]
i can also should just adapt the old code to the new environment only

**Comment by mhabimana** [comment]
@vralenkoane - Sounds great,let hear from Samuel

**Comment by vralenkoane** [comment]
Can I have someone to test the speed for the attached procedures. 
[script 1.txt](https://github.com/opencdms/Climsoft/files/1138127/script.1.txt)
[script 2.txt](https://github.com/opencdms/Climsoft/files/1138126/script.2.txt)

**Comment by mhabimana** [comment]
@vralenkoane - Thanks for the scripts. I am happy to test this by I really need some guidance on the best way to test this. Is it via visual studio or another package? @smachua and @isedwards  can advise as well.

**Comment by isedwards** [comment]
@mhabimana If you execute SQL in something like HeidiSQL or MySQL workbench then the software will report the query execution time, so this may be the best first step rather than timing the execution from within VB.NET. **vralenkoane** is probably executing the query against the small test database, so it would be really good if you could also test in on larger production databases from one or more countries if you have access to a copy of the data.

**Comment by vralenkoane** [comment]
Marcellin, Please change the last line of the script such that you call it with you station id. i.e. CALL Station_Missing_Data ('STATION_ID',STARTDATE','ENDDATE',ELEMENT_ID);

**Comment by mhabimana** [comment]
@vralenkoane - Well noted.

**Comment by vralenkoane** [comment]
Note not to execute the two scripts concurrently.

**Comment by mhabimana** [comment]
@vralenkoane - noted. I can see script 2 is pointing to obsinitial

**Comment by mhabimana** [comment]
@vralenkoane -Result-script1:
![image](https://user-images.githubusercontent.com/10340170/28067698-0591399a-664b-11e7-949c-c801596e43c3.png)

**Comment by vralenkoane** [comment]
how long did it take to complete?

**Comment by mhabimana** [comment]
@vralenkoane - Data for 1 year, element 5: around 21 secs.

**Comment by vralenkoane** [comment]
hmm, that super fast, script 1 or 2? Test them both?

**Comment by mhabimana** [comment]
@vralenkoane - Data for 1 year, element 5: script1: around 21 secs and script2: around 22 secs

**Comment by vralenkoane** [comment]
eish they look the same. Another important observation is that there are records were read value is null, is such a value missing?

**Comment by mhabimana** [comment]
@vralenkoane -How will it suppose to work? because I can see it has created a table of missing data in the data base. How was it suppose to work?

**Comment by vralenkoane** [comment]
my interest was on the time it takes to complete, the one with a shorter time is preferred. Script 1 creates table missing_data and populates it with all expected dates for data. Then checks observationinitial for missing days. finally the missing days are selected as out.

The other does a continuous date check for a data record and if there is no record returned, that record is locked into missing_data table. then select from missing_data.

@smachua how was the previous inventory approached?

**Comment by mhabimana** [comment]
@vralenkoane -Noted Do you mean "Then checks observationinitial for missing days." or observationfinal?

**Comment by vralenkoane** [comment]
i think it should be final? 

From Samuel, i needed to understand how he did it in v3

**Comment by mhabimana** [comment]
@vralenkoane - sounds great.

**Comment by vralenkoane** [comment]
I have realized that during data entry, the missing element are flagged 'M'. Do I have to concentrate only on Values flagged 'M' in the DB for Missing Data or records that are not in the DB ?

**Comment by mhabimana** [comment]
@vralenkoane -Thanks, yes missing data are flagged "M" in climsoft @smachua will be able to advise on this.

**Comment by mhabimana** [comment]
@vralenkoane - How is your progress on the inventory work? Though @smachua  has not yet replied on your question about missing data, I thing the best way is to concentrate on records that are not in the DB.
@smachua - Can you advise on this please?

**Comment by vralenkoane** [comment]
[Background Scripts.txt](https://github.com/opencdms/Climsoft/files/1294194/Background.Scripts.txt)

**Comment by mhabimana** [comment]
@vralenkoane -Thanks for the script.
