### ISSUE TITLE
Implementation of date picker in metadata information

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#204]
Is it possible to change the current settings of station opening and closing date in the metadata from automatic to manual or to leave this empty(blank) for climsoft administrator to define this instead of  giving this the default to the current date? I think this can lead to wrong information in the database. Your though on this please.

**Comment by isedwards** [comment]
@mhabimana I agree that ideally the date should not default to today's date, and this is something we should change.

From a technical perspective, the DateTimePicker included with WinForms must always contain a valid date (it is not possible to leave it blank - so this is why it has a default date).

A couple of possible suggestions:
- When the user clicks save we could give them a warning if the date entered is today's date, and ask them whether they are sure
- We could replace the built-in DateTimePicker control with a ["Nullable" DateTimePicker](https://www.google.co.uk/search?q=visual+basic+.net+Nullable+datetimepicker). We would have to choose one someone else has written, or implement on ourselves

**Comment by mhabimana** [comment]
@isedwards - Thanks for the suggestions. It makes sense.

**Comment by mhabimana** [comment]
@smachua - Are you happy to work and improve on the station metadata open and closing date feature? If yes,kindly assign this task to yourself (under assignee):
![image](https://cloud.githubusercontent.com/assets/10340170/26712533/f40370b6-476f-11e7-8fa7-c65c11874315.png)
