### ISSUE TITLE
Coordinates conversion features

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#205]
In version 3.2 there is a conversion feature  whereby if the user only knew the GPS coordinates in terms of Degrees, Minutes, Seconds they could enter those and the system would automatically convert them to decimal degrees.To me this is a powerful feature climsoft version 4 cannot miss since there are many National Meteorological Services(NMSs) which are still using these and are having their metadata in this format:
![image](https://cloud.githubusercontent.com/assets/10340170/26626838/2dc7c39e-4601-11e7-811e-049d1904eb85.png)

**Comment by isedwards** [comment]
@mhabimana - I agree that this is useful, and it would be easy to add.

I've added the `new developer` label as this is potentially something any of us could implement.

**Comment by mhabimana** [comment]
@smachua - Since we have source codes for this in earlier version (V3.2), I think this can be used as basis to add this feature in V4 instead of reinventing the wheel.

**Comment by isedwards** [comment]
@mhabimana, the maths for this is actually fairly straight forward. When using degrees, minutes and seconds, there are 60 minutes in 1 degree (and 60 seconds in 1 minute).  So the value in decimal degrees is:

`DD = degrees + minutes/60 + (seconds/60)/60`

Note that the seconds are divided by 60 twice to get the equivalent value in degrees and not just in minutes (which is what we would get it we only divided by 60 once), this is actually the same as...

`DD = degrees + minutes/60 + seconds/3600`

The N/S is then used to determine whether the value in decimal degrees should be positive or negative.

**Comment by isedwards** [comment]
@mhabimana - In the example that you've shown from version 3.2, it's not very clear when the latitude and longitude will be updated with the values that a user enters into the Degrees, Minutes and Seconds boxes.

In our new version, will the values be updated after every change (so if I enter 52 degrees first then the latitude becomes 52, then I enter 30 minutes and the latitude becomes 52.5 degrees, then I enter 0 seconds and the value stays at 52.5 degrees)?

What will happen if I already have a value of 53.5 in the latitude box? Will it be overwritten?

The latitude and longitude boxes are "first class citizens" (they are important as their values actually get stored in the database).  To calculate the latitude and longitude from other values I would probably expect to have a button (or one next to each field) each with a label like: "Calculate from DMS" and a tooltip to explain the meaning of DMS: "Calculate from degrees, minutes and seconds".

Clicking one of the buttons would open a small modal dialogue box to enter the values and then "Ok" to update the form below, or "Cancel" to change your mind?

**Comment by mhabimana** [comment]
In version 3.2 the way it works is that once you finish to type in Degree,Minutes,Seconds and select latitude(North(N) or South(S),the system convert automatically latitude to decimal and fill or update the Latitude text box, the same apply to the longitude,once you finish type in Degree,Minutes,Seconds and select longitude(East(E) or West(W),the system convert automatically longitude into decimal.

**Comment by isedwards** [comment]
It sounds like the value is updated when the N/S select box is changed.

What would happen if you typed in 9 degrees, 30 minutes, 12 seconds south (which would update the value) and then you changed your mind and changed 30 minutes to 32 minutes (how would you get the value to update?)

**Comment by mhabimana** [comment]
The GPS conversion feature program is ready for review. I tested it and it seems to provides good results though I realised that the coordinates (Lat/Long) was set to two decimal points in climsoft version 4 (e.g: Lat:-1.95/Lon:29.05). I set the data type to Double, so no limitation of decimal points. Any idea on how I can limit this as well to 2 decimal points?

**Comment by isedwards** [comment]
Although the Climsoft example database shows most station's lat/lon locations to the nearest two decimal places, I'm not sure that this will usually be the case.

When using [degrees of latitude and longitude](https://gis.stackexchange.com/a/8674/55042):
> - The first decimal place is worth up to 11.1 km: it can distinguish the position of one large city from a neighboring large city.
> - The second decimal place is worth up to 1.1 km: it can separate one village from the next.

In this case, when we are converting coordinates from Degrees Minutes Seconds (DNS) to Decimal Degrees (DD), the precision of the output should probably be determined by the precision of the input.  If the user is entering values with a precision to the nearest second then this is equivalent to 0.00028 degrees (or 4 to 5 decimal places).

> - The fourth decimal place is worth up to 11 m: it can identify a parcel of land. It is comparable to the typical accuracy of an uncorrected GPS unit with no interference.
> - The fifth decimal place is worth up to 1.1 m: it distinguish trees from each other. Accuracy to this level with commercial GPS units can only be achieved with differential correction.

To actually round the number to 2 or 4 decimal places you can use: `Math.Round(value, 2)` or `Math.Round(value, 4)`

**Comment by mhabimana** [comment]
@isedwards - Great thanks,let me try this.

**Comment by mhabimana** [comment]
@isedwards  - In this case the value is not fixed but variable????? How can I proceed?

**Comment by mhabimana** [comment]
@isedwards - Thanks it works

**Comment by mhabimana** [comment]
@isedwards - this PR was completed it is ready for review and merging.

**Comment by Patowhiz** [comment]
@mhabimana I think this was solved in the current version 4?

**Comment by mhabimana** [comment]
@Patowhiz :Yes
