### ISSUE TITLE
Import external data of different structure into climsoft version 4

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#206]
Currently,the import of external data  from CLICOM daily data, manual ingestion of Automatic Weather Station (AWS) data, Data from the National Oceanic Atmospheric Administration - Global Telecommunication System (NOAA-GTS) and the migration of data from previous versions of climsoft were implemented into climsoft version 4 under development. A routine to enable easy import of climate data with different structures than the ones mentioned above into climsoft version 4 is needed.

**Comment by smachua** [comment]
Coding completed. Awaiting merging on GitHub and testing by contributors

**Comment by mhabimana** [comment]
@smachua - Well done! Can you push now the task to the next level? (from the progress to review and testing).This is under project,code development.

**Comment by isedwards** [comment]
@mhabimana I've completed the review to accept Samuel's code.
When he has merged his pull request would you like to do some tests with Climsoft 3.2 data?  The new importer is accessible from the `Data Transfer` section under `External Data` > `Text Files`.  When you are happy (as the person who raised the issue) then you can close this issue.

**Comment by mhabimana** [comment]
@isedwards - Well noted.

**Comment by mhabimana** [comment]
@smachua - I am currently testing this feature before it is pushed to the last level of completion.Below is the error message I got for your advise:
![image](https://user-images.githubusercontent.com/10340170/27833801-f79d784e-60dc-11e7-9b72-1420920478a6.png)

**Comment by Patowhiz** [comment]
@mhabimana was this solved?

**Comment by mhabimana** [comment]
@Patowhiz :This was done . What is remaining is the import of Monthly data ( here, I assume some Met Services may have Monthly data only and not Daily,hourly or minutes data and wish to import these data into Climsoft.

**Comment by smachua** [comment]
@mhabimana it is better you close all those issues that have been solved to avoid complications.

**Comment by mhabimana** [comment]
@smachua : Noted.
