### ISSUE TITLE
The link to the Contributor License Agreement (CLA) on GitHub Read Me file  is pointing to the wrong site.

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#207]
I realized  that the Contributor License Agreement (CLA) link under ReadMe file on GitHub is pointing to the old climsoft project on met-elearning. Here is the correct one pointing to the climsoft project on met-elearning site: 
http://www.met-elearning.org/moodle_v2/mod/assign/view.php?id=3153

**Comment by isedwards** [comment]
@mhabimana - when a visitor is not logged into met-elearning, they see a summary page that says `Now enter this assignment and upload the file through the "Upload a file" link below.`

Do you think this is this okay, as most visitors won't have a login, or does the page also need some instructions on how to get a login for the site?

**Comment by mhabimana** [comment]
@isedwards - Thanks, you are right,the page needs  extra instructions (including the link) on how to get a login for the site. I need to update the page by adding these.

**Comment by mhabimana** [comment]
@isedwards - Additional instructions were added on how to get a login for the site and submit the CLA.

**Comment by mhabimana** [comment]
@isedwards - The CLA link  on GitHub is still pointing to the wrong site.This need to be updated.

**Comment by mhabimana** [comment]
@isedwards - How far have you gone with fixing this issue?

**Comment by mhabimana** [comment]
@isedwards - Thanks to resolve this issue.
