### ISSUE TITLE
Deleting a station

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#212]
**1.Stations with no data in the database**
If you delete the last station record in the metadata(station), the screen will not refresh and you will still see the deleted record on the screen.  In this case you should use the navigation buttons to go to the previous record. If you click on Delete a second time the system will tell you that “There is no row at position.  Need a screen refresh at this point. There should be a confirmation message to ask if you really want to delete this station – otherwise I can imagine accidents happening.
![image](https://user-images.githubusercontent.com/10340170/27377516-dd5365d4-567d-11e7-866c-a0a417f9e3f3.png)
**2.Stations with data in the database**
When clicking on Delete button,the message below appear.this message is not clear,there is need for a clear and informative message to climsoft users:
![image](https://user-images.githubusercontent.com/10340170/27378531-ddb605ba-5680-11e7-9438-54eade8676d3.png)
 3. **Deleting element** 
The same case  mentioned above is applied to the element. An automatic refresh would be useful in this case.

**Comment by Steve-Palmer** [comment]
For stations with data in the database, deletion of the station should not be possible. If a station has been created in error, and had data assigned to it, then the process must be to delete the data, and then to delete the station. This should only be possible by a manager with sufficient authority. Hence the error message should say something like "This station has observation data, therefore it cannot be deleted. Consult the authorised Network Manager."

**Comment by mhabimana** [comment]
@Steve-Palmer -Sounds great.
