### ISSUE TITLE
Table Driven Code Forms(TDCFs)

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#215]
Table Driven Code Forms (TDCFs) is one of the great features of climsoft. It working well with the current climsoft v3.2 and It is being used by NMHSs to encode and  exchange climate data at national,regional and global level (GTS). It has not yet being implemented in climsoft version 4.
![image](https://user-images.githubusercontent.com/10340170/27581584-bc8a007a-5b36-11e7-8443-b159abfb6369.png)

![image](https://user-images.githubusercontent.com/10340170/27581744-34fbf4aa-5b37-11e7-9b86-4ea21e90b9f4.png)

**Comment by Patowhiz** [comment]
@smachua is this now implemented in CLIMSOFT version 4

**Comment by smachua** [comment]
@Patowhiz yes for Synoptic messages but am working on CLIMAT messages.
