### ISSUE TITLE
Encrypted connections - MITM attack vulnerability

### ISSUE THREAD

**Issue by isedwards** [opencdms/Climsoft#223]
Climsoft 4 uses an unencrypted connection to the MySQL database. All queries and responses are [sent in plain-text](https://forums.mysql.com/read.php?30,372341,374096), with the exception of the user's password which is sent as an [SHA1 Hash](https://en.wikipedia.org/wiki/SHA-1).

This leaves us vulnerable to data hijacking and man-in-the-middle (MITM) attacks.

The issue can be fixed using [MySQL over SSL](https://dev.mysql.com/doc/connector-net/en/connector-net-tutorials-ssl.html), although this adds to the complexity of deployment in-country, especially when setting up database servers.

> By default, MySQL uses unencrypted connections between the client and the server. This means that someone with access to the network could watch all your traffic and look at the data being sent or received. They could even change the data while it is in transit between client and server.

The examples below show the interception of Climsoft data being transferred over the network.

**Example 1:**
![root_login](https://user-images.githubusercontent.com/2097922/28207946-6876f6dc-6883-11e7-95d7-ea44ad845b72.png)

![wireshark_auth_root](https://user-images.githubusercontent.com/2097922/28207959-6fcc9202-6883-11e7-9b59-7391124a30f7.png)

**Example 2:**

After logging in, clicking on `Metadata Information` results in:

`SELECT elementId FROM obselement ORDER BY elementId`
being sent in plain text.  MITM attack could replace his with arbitrary command, e.g. `DROP TABLE observationfinal` (or something more malicious).

![wireshark_metadata_select](https://user-images.githubusercontent.com/2097922/28208163-55705aaa-6884-11e7-975c-eed04efebcad.png)

An unencrypted connection is usually [considered acceptable](https://stackoverflow.com/a/11192872/) when the database and client are only ever located on the same machine, and the database is not internet-facing.

See also: [GRANT REQUIRE SSL;](https://dev.mysql.com/doc/refman/5.5/en/grant.html#grant-other-characteristics)

**Comment by mhabimana** [comment]
@isedwards - Thanks for this observation.

**Comment by isedwards** [comment]
In Climsoft v4.x and v5.x we recommend that Climsoft Desktop is only used over a secure local area network (LAN) at a particular site, or over a virtual private network (VPN) when used from an external site connecting of the internet.

Climsoft version 6 will support secure connections over the internet
