### ISSUE TITLE
Quality Check Range Specification

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#233]
The current QC Global Limits and Inter Element Comparison Checks implemented in Climsoft version 4 does not give room to users to specific station(s) to check but rather they prompt users to do QC for the entire stations in the database. Since users may be interested to do QC for a particular station(s) it would be great to give her/him an option for this(Below I highlighted additional element which are not yet implemented on this form and required to be added to respond to this issue:
![image](https://user-images.githubusercontent.com/10340170/29825717-e77ba850-8cdd-11e7-9ccc-db01cee7ab93.png)

**Comment by Fortunata** [comment]
True  as we practiced on the V4 , there was no room for the user to select a one station to perform quality control. More often than not User tend to work on one station cleaning their data but for a specified period . It is  good Marcellino to start on this interface providing users with an option to select one station.
