### ISSUE TITLE
Correcting misplaced data in CLIMSOFT

### ISSUE THREAD

**Issue by rdstern** [opencdms/Climsoft#237]
A number of years of data were "one-day-out".  The rainfall is recorded in the morning and then should be entered onto the sheets (and the database) for the previous day.  This was not done in some of the stations, and for a period of several (consecutive) years.
I wonder how this could be corrected in CLIMSOFT in a reasonably efficient manner.  It is easy, but risky, to export and then make the change in the data once the rainfall is in a single column.  It would be good to have an option in CLIMSOFT at least at the month level.  Could this be discussed.  It is certainly not urgent, i.e. not for 4.0. 

But it would be part of the provision of facilities to make common corrections easily into the CIMSOFT database itself.

**Comment by mhabimana** [comment]
@rdstern - Sounds great. Well noted

**Comment by Steve-Palmer** [comment]
This correction was done in the Met Office as part of the bulk loading of data from the previous Rainmaster database to MIDAS. The policy for daily rainfall and max temperature (but not min temperature) was that on daily paper records, the reading was "cast back" to the day before the date when the reading was made, and Rainmaster held rainfalls by the start of the period, but this leads to anomalies with missing data. For MIDAS (and Climsoft follows MIDAS) it was decided to hold all data by the date/time of reading. Hence the change was done once as part of the bulk transfer.
There is a remaining issue where mistakes are made, and the recorded data is off by one day. This is a QC issue. I think we already have a QC flag which shows when the date/time has been corrected.
The question then becomes - should we have a facility in a QC dialogue to shift all the daily data in a month by one day forward or backward as a single operation? Of course this would need to remind the QC operator to check the previous and following month too.

**Comment by isedwards** [comment]
This issue will be resolved by #486
