### ISSUE TITLE
Implementation of Delete Cell and Insert Cell Buttons on Data Key Entry Forms in Climsoft V4

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#286]
The two commands are working very well in Climsoft V3.2 whereby **Delete Cell** shift all the data at once in the cells upward in the previous cells and **Insert Cell** shift all the data at once in the cells downward. This is still very important and need to be implement in climsoft V4  to save time during data key entry process ;
![image](https://user-images.githubusercontent.com/10340170/37508034-5a51153e-2902-11e8-9290-26662811013e.png)

**Comment by Patowhiz** [comment]
@mhabimana in the insert cell scenario, you mean the value of day 01 to go to day 02, the value of day 02 to go to day 03 and so on? If so then what happens to the value of day 30 if it happens to be there? Is it discarded?

**Comment by mhabimana** [comment]
@Patowhiz: Exactly,you get the point. Most of the time,Data entry clerks realise this mistakes  at the middle of typing or before reaching very far in typing on the form,and instead of re-typing,this methods is used. I think if the value exist already,the system can just overwrite this with the new values.Hope this makes sense.

**Comment by mhabimana** [comment]
@Patowhiz: I think,we can maintain these like this,unless you want to suggest new names.

**Comment by Patowhiz** [comment]
Should they be able to shift the values from a specific day (either upwards or downwards) or we limit them to shifting from just the first day that has a value to the last day that has a value?

**Comment by mhabimana** [comment]
@Patowhiz : The first option would be great; shift the values from a specific day (either upwards:Delete Cell) or Insert Cell:downwards).

**Comment by Patowhiz** [comment]
@mhabimana I'm thinking of having this as a **right click menu** on the **individual** text boxes to shift from. For  instance if you want to shift from day 09 upwards, you right click on the day 09 textbox, which will show a context menu with 2 options , 
  shift values upwards 
  shift values downwards
Depending on the clicked option, the values will be shifted based on that text box ...

What do you think about that?

**Comment by mhabimana** [comment]
@Patowhiz : Sounds very great. no problem. Go ahead.so longer us this work well as desired.

**Comment by Fortunata** [comment]
This kind of  shift up or down was there in CLICOM and if added to Climsoft it will improve performance of the software.This also need to be put in user manual once implemented.

**Comment by Patowhiz** [comment]
I now have this in a right click menu
