### ISSUE TITLE
Merging Codes ,Installer for Climsoft V4.1 and Testing

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#311]
Dear Team members
Happy to see that both codes are merged and working well. Here are the remaining tasks:
1.Finalise the upload data transfer progress dialog;
2. Adding codes for Victor on "Data Gaps" and "Double Key Entry" by Samuel;
3.Create the Installer for Climsoft V4.1;
4. Avail the Installer for testing in Western Kenya and  to Climsoft Contributors.
@maxwellfundi @Patowhiz let us know when (1) will be ready
@smachua let us know your view on (2)
Your feedback will help us to know when the setup will be ready for sharing for the testing exercise but the earlier the better for the testing.

**Comment by smachua** [comment]
@mhabimana, @Patowhiz and @maxwellfundi I will be able to implement 2 if you're the forms are working as expected. I just need a day or 2 to accomplish that.

**Comment by mhabimana** [comment]
@smachua Thanks and noted.

**Comment by Patowhiz** [comment]
@smachua @mhabimana   I'm working on the progress bar. It should be ready by this weekend

**Comment by mhabimana** [comment]
@Patowhiz Thanks,well noted.
