### ISSUE TITLE
Delete Rainfall Value - Form Daily2

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#323]
@maxwellfundi @Patowhiz  Currently with the new Daily2 Data entry form,it is not possible to delete the rainfall values using delete button. This will not accept unless you fill the total box.  Since this total is just for checking and is not stored in the database,the Delete command button should delete the data displayed on the form without prompting the user to fill the total box. Correction is needed here.

**Comment by Patowhiz** [comment]
@mhabimana I just finished solving this issue. Should I hold to the changes or a create a new pull request on this?

**Comment by Patowhiz** [comment]
I'm not sure if the files touched in  PR #302 will affect the data entry forms
