### ISSUE TITLE
What is provided as a CLIMSOFT release?

### ISSUE THREAD

**Issue by rdstern** [opencdms/Climsoft#325]
Following the last message from Samuel in #321, we are agreed on the "Version" of the code to be provided for the testing in Western Kenya.  He writes:

"However I agree with you that:
-Western Kenya testing can start even without merging the recent changes. The new key entry forms were the target of testing."

This message is to clarify exactly what is to be provided and where it is provided from.

1. **First the code from the master branch.**  In R-Instat what we do is to create a release on GitHub which stores the state of the code at the point a release is made.  This is then compiled into an installer which is uploaded to the R-Instat website for users.  This seems consistent with your scheme [here](https://github.com/opencdms/Climsoft/wiki/Software-Release-Process).  
2. We add a **document with the list of issues fixed** since the previous release.  This may not be needed here for Western Kenya, but having some document in preparation for this for Rwanda, would be useful.
3. **We have an installation guide**.  You have one for Version 3.2.  Is it updated for Version 4.1?  I would like the applications team in Western Kenya to install, hopefully without help needed by Maxwell or Patrick.
4. I assume the **main database will be empty**?
5. We have an "Open from Library" and in CLIMSOFT this is the parallel of your **tutorial database**, discussed in #268.  I assume this tutorial database is provided and users can switch between the initially empty database and the tutorial database. 
6. On the CLIMSOFT web site and Moodle site there are (correctly) still all the **guides** for Version 3.2.  What is provided for this version?

I agree that the main testing in Western Kenya is on the data entry.  If their time permits hey will also use the opportunity to explore and test other components.

**Comment by mhabimana** [comment]
@rdstern Thanks I agree that we are going to compile a setup from the master copy the way it is now for testing in Western Kenya though this is not what was desired initially. We were supposed to create the installer from the merged version ( some important work are not yet merged). In this regards,I will share with the team the Dropbox link containing both the installer and the user Manual documentation for CLIMSOFT Version 4 ( the installer will be packed with the operation database(empty) and the test database containing test data. I hope this will be enough by now. This  will be shared to you not later than tomorrow.
