### ISSUE TITLE
Importing text files

### ISSUE THREAD

**Issue by rdstern** [opencdms/Climsoft#337]
This is an issue for our team and we just need a bit of help.

We have data from Western Kenya for 52 stations.  We have imported the Station file into CLIMSOFT.  Now we want to import the data - about 600,000 records of rainfall.  Another file has about 60,000 records of many elements, but we want to start with the rainfall.

Can we import directly, using your information from Section 8.5,  or do we need to complete the **station element** information first?

**Comment by mhabimana** [comment]
@rdstern Thanks. Station element is not required.If you have successfully imported your metadata for station (stationId,stationName,Lat,Lon,elevation),this should be enough for you to import your data into climsoft. Make sure the elements codes match with the one in climsoft.

**Comment by rdstern** [comment]
Many thanks.  That's a relief.  We have had another small problem that the Station file has matching names to the ones in the Station information.  But it doesn't have an ID in the data file.  We have linked on Station name.  I presume we have to add the ID variable into our station data file

**Comment by mhabimana** [comment]
@rdstern The Stationid is very important and I suggest you to define some station id for the stations you are going to import for the matter of testing before importing the stations metadata info.

**Comment by rdstern** [comment]
Thanks.  Will do.
