### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by rdstern** [opencdms/Climsoft#338]
Many operations can't be done, because I have not gone in with Administrator privileges.   
For example when I ask for a simple product - an Inventory - it says:

**ClimsoftVer4
Access to the path 'C:\Program Files (x86)\ClimsoftV4\Bin\data' is denied.
OK**   

This applies to many operations using either the tutorial or the main database.  That is something that I suggest be fixed before Rwanda.

Just to be clear I am here talking about Windows "Adminstrator" , not the level of user in CLIMSOFT.

**Comment by rdstern** [comment]
Now I see part of this problem with the products.
I have been producing products and an inventory.  They are saved automatically here:
**C:\Program Files (x86)\ClimsoftV4\Bin\data**
This is why I was not able to use the products without being a (Windows) administrator.

This should be changed.
At the same time we should look at what else needs this access and minimise the need to be a Windows administrator.

**Comment by rdstern** [comment]
I'm just checking - with all the changes made, I wonder what has happened on  the access to various parts of the software for those who don't wish, or need to have administrative privileges.  I found it was needed to switch to the test database, and that seems unnecessary.  More than that, see above is the need when accessing some products.  

I am just checking that this has now been addressed.  If so, then this issue can be closed.

**Comment by mhabimana** [comment]
@rdstern Thanks for your observation,however,part of the installation process is to give the computer user **the right** to **climsoftV4** folder and sub-folders,this is done once. the process to give permission to a computer user is in the last para of the climsoft readme file produced during the installation (attached) and will be added as well in the user manual and guides.

**Comment by smachua** [comment]
@rdstern before the issue is closed there some issues raised by @mhabimana that were not completely solved by PR #365 that am working on. I will be through today. If @mhabimana will be satisfied then the issue can then closed.

**Comment by rdstern** [comment]
Now I think Samuel has made some changes.  I want to check we are discussing the same issue.  I am here considering **Windows** administrator rights, not the permissions for different users of CLIMSOFT.

@mhabimana  could you please say what this now means, in terms of the issue.  Can a user now use the test database without having **Windows admin privileges**, and what about **producing products**?  In the version we tested you also needed to be a **Windows administrator** there. 
I assume the installer still needs to right-click at the start and have **Windows administrator** rights.  But then the general use of CLIMSOFT no longer needs this.  Am I right?

**Comment by mhabimana** [comment]
@isedwards You are right 100% when it comes to the installation.

**Comment by rdstern** [comment]
And what is the situation when getting products and also when switching to the test database?  In the version we tested there seem to be lots of places in the current CLIMSOFT when you need to have Windows Administrator privileges.  I assume that has now changed, so you only need to be a Windows administrator for installation. Please confirm that too.

**Comment by mhabimana** [comment]
@rdstern You are right,but you need to give the computer user permission to access the contents of the climsoftv4 folder and sub folders (if you are not the computer administrator) as explained in the readme file attached to this issue.

**Comment by smachua** [comment]
@rdstern Windows permissions require to be set for all climsoft users in windows as described in the file "Readme_Climsoft_V4.txt" that comes with Climsoft installer. Refer to paragraph 4(iii) of that document. The permissions should be set soon after installation. But they can still be set later. Of course the windows administrator has the overall permissions.

Windows permissions are required for saving files in Climsoft path (i.e. ClimsoftV4). In particular, files for products and database connection details.

Rights to access different Climsoft menus depend on Climsoft user types.  There were some issues on this especially when using test database but now they have been resolved.
