### ISSUE TITLE
Uploading daily data

### ISSUE THREAD

**Issue by Wycklife** [opencdms/Climsoft#339]
I have imported the station information, and am trying to import the daily data. It is about 627000 records.

I keep getting the message:

**ClimsoftVer4
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
OK**   

Is there an obvious reason for this?

**Comment by mhabimana** [comment]
@Wycklife Can you add the screenshot of this error to help us diagnose this?

**Comment by Wycklife** [comment]
![image](https://user-images.githubusercontent.com/33898404/44728425-2af91600-aae5-11e8-8d67-3dae40c8eeca.png)
Here is the screenshot of the issue.

**Comment by Wycklife** [comment]
[WKenya_StationInfo.xlsx](https://github.com/opencdms/Climsoft/files/2331129/WKenya_StationInfo.xlsx)

Importing the above station metadata, was successful. When i tried to import rainfall data of the stations,
the above error occurred again, and the data was loading extremely slowly. Below is the screenshot of the above issue.
![image](https://user-images.githubusercontent.com/33898404/44772359-4d873f80-ab76-11e8-87c8-e6ed7a40eb3c.png)
The file containing this data set is large and i'm sending it via the email.

**Comment by mhabimana** [comment]
@Wycklife Have  you used the User Manual section on this?Especially on the column header settings?It is clear that you have not matched well your data with the corresponding elements under **column header settings**

**Comment by Wycklife** [comment]
Hi,
The attached below is the file containing the data set,
 Wkenya_Rain2.xlsx
<https://drive.google.com/file/d/1R6BZ4He-RIcNq8JVl5oYtoqC0rMw7FP1/view?usp=drive_web>
Regards,

**Comment by mhabimana** [comment]
@Wycklife You need to do a bit of work on this file before the import into climsoft. There some column which are not needed and you need to match well the column (see below dialog). Just take a few minutes and read the user manual section on this:
![image](https://user-images.githubusercontent.com/10340170/44779528-64369200-ab88-11e8-8e04-0f02c9609939.png)
