### ISSUE TITLE
Products > data > Daily dialogue

### ISSUE THREAD

**Issue by rdstern** [opencdms/Climsoft#348]
I can not get this dialogue w=to work any more.  I am not sure what I am doing wrong:
![image](https://user-images.githubusercontent.com/11226469/44806986-0aa68580-abd1-11e8-8e39-1a4662890dcf.png)

This is from the Tutorial database.  I transferred that into R-Instat, (a different way) so I know there are data at that station.  I have tried other things and the message is always the same.  It always says there are no data.

Minor issues are the behavior of the Select Station and Select Element pull-down menus.

In Select Station it lists all the Stations (I added those from Western Kenya so there are a lot. - over 60.)  When I choose the Select All Stations it only selects the 12 that were in the database originally.  That is actually sensible, because the others have no data in - so I wonder if that is what it is doing.  If som then why does it include them in the pull-down list?

Also it only allows me to select by the Station name.  (Other dialogues only allow the ID) When selected it shows both - which is great.  Could it please show both in the drop down?

the select elements is the other way round.  The drop down only has 3 elements, tmas, tmin and precip.  Here when I Select all elements it selects 29.  Again that is sensible, because 29 elements have data.  But there is no way to select other than the 3 main ones from the drop down.

**Comment by mhabimana** [comment]
@rdstern Re-the dialog above. Are you sure you are pointing to the right database(here, I mean the test database)? Because,I tried to query the same station and the same period using the test database and I am able to get the output file. Please check well.

**Comment by rdstern** [comment]
Yes, I have checked with Administration > Configure Database Connection and it is the test database.
We were earlier able to export data nicely from the tutorial database, (on another machine).  That was before we added the station records from Western Kenya.  In my current test database I therefore do have lots of stations with no data.  I just wonder whether there is a problem somewhere there.  It might be good to check by adding some stations, and then trying again with the same station.

In there new stations we have added, they do come first in the station list.  So it could be good to either add those stations, or at least some with a smaller ID than the 12 already there?

**Comment by mhabimana** [comment]
@rdstern I think the issue is clear now. Changing the database connection using the administration menu is still an issue unless if you close the software and start this again. This use to work very well but since the idea of EF was introduced, it is not longer possible to switch database using the administration menu. This is an issue which need to be addressed.
