### ISSUE TITLE
Starting again with the tutorial?

### ISSUE THREAD

**Issue by rdstern** [opencdms/Climsoft#352]
We have been using both the empty database and the test (tutorial) database.  We would now like to start the tutorial again.  And go back to the empty database, now we know more about how to use CLIMSOFT.

Is there a "backup" copy of the databases as they are originally supplied?  If not, then could there be, in the future?  Perhaps even in  the version for Rwanda.

**Comment by mhabimana** [comment]
@rdstern The software is distributed with the script to create the database(both the operation database(empty and the test database) this is located in the climsoft folder DBase. So, in case of any thing goes wrong,this is where to go. In this case,you can run again this script to create fresh databases(operation and test database).
