### ISSUE TITLE
List of bugs observed in the master which need to be addressed.

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#354]
Below is the issues/bugs which are in the master and need to be addressed. However, 2,3 and 4 were addressed by Samuel in the beta2 Pull Request committed by Samuel (#324):
1. Deleting rainfall records on the Form Daily2: This cannot be deleted unless the required total value is provided in the total required text box;
2. There is an error message which occur when attempting to open the form Synop_2_ra1,this error message was raised in (#350) this error occur because the following flags (Flag 178, Flag 179, Flag 180 ) were removed in the database schema, in form synop_2_ra1 table because they are not required in the form synoptic_2_ra1 but they are still there in the Entity Framework (EF);
3. Form hourlywind: Displays a bug when there is a case of missing value (M) in the form; this bug need a fix;
4. Observation Hours (HH) on Data entry Forms should be set from Hour 00 to Hour 23 instead of Hour 1 to Hour 24 (currently).

**Comment by mhabimana** [comment]
@Patowhiz @maxwellfundi: On the above list number 1 is still pending.I wonder if you have time to work and address this.

**Comment by Patowhiz** [comment]
I solved item 1 and 2 longtime ago. Let me push the changes.

**Comment by mhabimana** [comment]
@Patowhiz Great thanks.Go ahead.

**Comment by smachua** [comment]
@Patowhiz thanks. Please push the changes and let Mracellin review and commit them. Inform us when you're through.

**Comment by Patowhiz** [comment]
@mhabimana which form has Hour 01 ?

**Comment by mhabimana** [comment]
@Patowhiz This was fixed by @smachua and now working well in the master:see below,before it use to be hours(HH) starting from 1 to 24 but now it is working well on tall the forms from 0 to 23
![image](https://user-images.githubusercontent.com/10340170/44979943-22865c80-af77-11e8-8175-326d347459fc.png)

**Comment by Patowhiz** [comment]
Wow! Thats nice. I'm glad @smachua was able to go through the ucrHour contrrol code and easily fix this. Perfect.

**Comment by smachua** [comment]
@Patowhiz I suggest that you clone the master then fix 1 and 2 from there. Note that we have already merged both your code and ours as it was before the testing started. Therefore your branch is far behind the master and may course problems.

**Comment by Patowhiz** [comment]
Okay. I'll delete the pull request once I'm done cloning

**Comment by mhabimana** [comment]
@Patowhiz No problem.

**Comment by smachua** [comment]
@Patowhiz please note that I solved problems 3 and 4 by modifying the code for ucrHourlyWind and ucrHour respectively. You may check the simple modifications done in sub 'PopulateControl' in both user controls.

**Comment by Patowhiz** [comment]
@smachua  I've noticed that you made several changes . I'm obliged to ask what this code block is for in ucrHourlyWind populate control sub

```
  If frmNewHourlyWind.chkRepeatEntry.Checked Then
            Me.Clear()
            Me.ucrDirectionSpeedFlag0.ucrDDFF.GetFocus()
            With frmNewHourlyWind
                .btnAddNew.Enabled = False
                .btnSave.Enabled = False
                .btnUpdate.Enabled = True
            End With
        End If
```

**Comment by Patowhiz** [comment]
@smachua  The changes that you made in `ucrHour` are okay. i.e changing the loop from 0 to 11 instead of 1 to 12.
But the changes for fixing the flag issue in `ucrHourlyWind` are not quite okay. The bug is in `ucrDirectionSpeedFlag`. I'll be reverting this back to the way it was and fixing it at the `ucrDirectionSpeedFlag` level

**Comment by Patowhiz** [comment]
@smachua I have also noticed that you added 2 subroutines in the ucrDirectionSpeedFlag control, sub `Compare_Entry` and sub `Validate_Entry`. Is there something that we missed?

**Comment by smachua** [comment]
@Patowhiz that's a very good observation.  The 2 subroutines are for linking the New Forms with the double entry routines. You'll find them also in other forms. Let them stay since they have been tested and found to work well. Double key entry now worksok with the new forms. I will soon give a demo on how the operation works.

**Comment by smachua** [comment]
Thanks @Patowhiz. Am happy we're now working on the same code perfectly.

**Comment by Patowhiz** [comment]
Item 2 can only be fixed at the EF and database level

**Comment by mhabimana** [comment]
@Patowhiz There is an issue of rounding observed by @rdstern which can be sorted out as well see below: This is a serious issue especially on rainfall data where by the total display 52 and yet it should be 52.3 Though the total value will not be stored in the data base but the total should display exactly the way it is and not rounding as it does in this case. 
![image](https://user-images.githubusercontent.com/10340170/44993639-fa612280-afa3-11e8-8fd5-29da25be1470.png)

**Comment by Patowhiz** [comment]
Okay, I'm checking this now. Are the other changes okay?

**Comment by Patowhiz** [comment]
@smachua could you share the latest test script so that I can update my database

**Comment by mhabimana** [comment]
@Patowhiz Thanks, I think it is OK for the total since there is a column to store this value although it is not supposed to be stored in observationinitial table

**Comment by Patowhiz** [comment]
Is the issue of total found during validation or during display?

**Comment by mhabimana** [comment]
@Patowhiz This is during display and this is the value stored in the total box.I think the issue here is the data type.

**Comment by mhabimana** [comment]
@smachua @Patowhiz There is no place to adjust sequencer for the year. I wonder how this can adjust because it is not under tool,sequencer configuration and yet it is set to work with the sequencer for the year.I think that why Add New button is not working.

**Comment by Patowhiz** [comment]
@mhabimana yes! The formMonthly relies on table `seq_year `as it's sequencer.  @isedwards Right now that table is not in the Entity Framework and therefore even after setting up the years in the table the add new will still not work. Once that is fixed, then add new will work just fine.

**Comment by mhabimana** [comment]
@Patowhiz  Thanks to fix the rounding issue in the total tex box (form daily2).Sorry, I reopen this because number 2 is still pending and need a fix.
As per your request,attached is the latest database script we are using,remember to change the extension txt with sql before running or loading the attached script.
[mariadb_climsoft_db_v4_all.txt](https://github.com/opencdms/Climsoft/files/2347318/mariadb_climsoft_db_v4_all.txt)

**Comment by rdstern** [comment]
Good to see the continuing progress.  Just a small query that this correction is on the same Master that we tested last week on the Western Kenya data?

**Comment by mhabimana** [comment]
@rdstern The correction is on the master.

**Comment by mhabimana** [comment]
@Patowhiz @smachua I discover the issue in form_synop_2_ra1,this was not updated in the recent database script( flag 169,170 and 171) were added and then flag 178,179 and 180 was removed because the don't have any role to play. So the EF is OK,what we need to do is just to add these in the synop_2_ra1 table.

**Comment by Patowhiz** [comment]
So this form has not been tested at all?

**Comment by smachua** [comment]
@Patowhiz and @mhabimana I plan to modify sequencer for the Form Monthly to include the element code i.e. seq_element_year instead of the current seq_year. In that case I will add a dialog in General Settings where the element codes can be sequenced. The year should be the one following the latest record.
Meanwhile sequencing can be done on the year and the user selects the appropriate element.

**Comment by smachua** [comment]
@mhabimana and @Patowhiz . Attached is the script for both databases. Let me know if it's ok with you.
[mariadb_climsoft_db_v4_all.txt](https://github.com/opencdms/Climsoft/files/2347846/mariadb_climsoft_db_v4_all.txt)

**Comment by mhabimana** [comment]
@smachua  Sounds great. If I get you well,you are suggesting that this form be used they way it is now or the improvement you are suggesting will be done very soon? Please let us know.

**Comment by mhabimana** [comment]
@smachua The script is now working well with the data entry forms on both test and operation databases.I going to remove what I posted earlier to avoid any confusion.

**Comment by Patowhiz** [comment]
@smachua the latest script doesn't have stations

**Comment by mhabimana** [comment]
@Patowhiz the default database is not the test database,please change this at login by pointing to the test database.

**Comment by Patowhiz** [comment]
All the data entry forms are working well on my end. @smachua @mhabimana I've noticed an addition of a disabled checkbox named Repeat Entry, probably a new feature that was required later? I've also noticed a new entry form, form_agro1 which doesn't use the custom controls. I would like to point out that the form functions slightly different form the others in areas like validation.

**Comment by smachua** [comment]
@Patowhiz and @mhabimana the additional checkbox is part of double key entry operations and should not worry you. The form_agro1 was urgently implemented as a request from KMD while you were still working on the new ones. Although it looks a bit complicated we can later discuss how you can redesign it to have the custom controls.

**Comment by Patowhiz** [comment]
Okay

**Comment by mhabimana** [comment]
This was addressed and can now be closed
