### ISSUE TITLE
Upload Button and the climsoft operator

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#360]
@Patowhiz The upload button should not be active for the user with the role of climsoft operator since his task is to keying in data and save only. Climsoft supervisor has to check the entered data and once he/she is happy then use the upload button to transfer these data into observationinitial table. Change is needed (below is the error I got when the upload button was clicked,of course logged in with this user:operator).
![image](https://user-images.githubusercontent.com/10340170/45087170-ab370100-b10d-11e8-8b7d-66d2301884c6.png)

**Comment by Patowhiz** [comment]
I've noticed this includes deleting too

**Comment by mhabimana** [comment]
@Patowhiz You are right

**Comment by maxwellfundi** [comment]
@mhabimana We had no knowledge of that aspect yet. Good that you pointed it out and now its fixed by @Patowhiz thanks.
