### ISSUE TITLE
What should be captured in "Total" box when all the daily data is missing for one particular month

### ISSUE THREAD

**Issue by MainaJohnO** [opencdms/Climsoft#362]
![missing values for the whole month_total m](https://user-images.githubusercontent.com/32262789/45096152-8c923380-b128-11e8-890f-e9c30d1b090d.PNG)
When entering missing data for a case of daily data missing for all the days in one month, the missing is flagged off as "M" as in the attached picture. My understanding in this case is that the total should as well be flagged as "M" but when try save the error messaged captured on the picture pops up. How then should  the total box be filled? The same message also appears when I try to fill the total by "0"

**Comment by mhabimana** [comment]
@MainaJohnO Thanks for this observation. There is no need to fill the form if there is no data for a whole Month.

**Comment by Steve-Palmer** [comment]
One of the key principles in climsoft is that there is no data in the database when the data is missing. The data model includes the observation schedule which tells the user what data ought to be there, so it is possible to report what data is missing.
An advantage of this approach is that there is no possibility of mistaking a "missing data" flag for real data. In other CDMS, missing data is indicated by a flag value such as "999", with obvious dangers.
