### ISSUE TITLE
Exit/Close Climsoft program

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#370]
Climsoft Main Menu has got 2 options to exit/close the program; the **close** button and the **X** sign at the top right of the dialog. However, I have realised that when you choose the X sign, the dialog closed but still the program is running in the background but when close button is selected the program shut down completely. Most users are not aware of this and you may find because of using the X sign there is more than one instances of the program running in the background which might be the source of program crashing or not responding. I am suggesting that the X sign be disabled or removed and we remain with the close button or to program both Close button and X sign to perform the same task of closing/shutdown completely the program.
![image](https://user-images.githubusercontent.com/10340170/45533248-ae15ae00-b7ff-11e8-8942-43cdb562586f.png)

**Comment by smachua** [comment]
@mhabimana and @rdstern I am going to address those issues.

**Comment by isedwards** [comment]
@mhabimana are you going to assign this issue to Samuel?

@smachua, what are your thoughts on addressing this? Will you remove the red close button (as per Roger's feedback) and fix the problem with the close button in the top right?

Clicking the close button in the top right currently doesn't end the program because some windows (like frmLogin) are still open but hidden.  There are currently several places in the code that require frmLogin to not be closed because values are read from the controls on the form, but this could be changed.

**Comment by mhabimana** [comment]
@isedwards Thanks Ian to shade more light on this. I wonder if the X sign can be disabled or removed so that the close be used instead because the idea is to close the program completely( and the close is doing this action). I am happy to assign @smachua this issue but if he is very busy he can let us know so that this be addressed by others. We are remaining with only a week before the Rwanda visit.

**Comment by smachua** [comment]
@mhabimana and @isedwards unless there is a different opinion from Roger's am going to replace the close button with a more friendly one. Am also going to ensure that when the form is closed through any method the entire Climsoft application closes.

**Comment by mhabimana** [comment]
@smachua Thanks,I think this is what we need.So go ahead and do this.

**Comment by isedwards** [comment]
I like the idea of making the close icon in the middle of the main menu more friendly.

I think @mhabimana's suggestion of [disabling the close button](https://www.codeproject.com/Articles/20379/Disabling-Close-Button-on-Forms) ('X') on the top right of the main menu form is very sensible and worth considering... on all other forms this button is used to close the current form, whereas in the main menu it would close the entire applucation even if other forms are currently open which is a bit unusual.

**Comment by smachua** [comment]
@isedwards and @mhabimana since main menu form is the entry point to all other forms, menus and dialogs I find it logical to end anything else when it closes. Like other Windows applications I would rather not disable the close button ('X') but leave it to exit Climsoft.

**Comment by mhabimana** [comment]
@smachua I am not getting you well here. Do you mean remove the **close** button and let the **X** terminate completelyclimsoft program? ( hear I mean stop even the program running in the background). Please let me know.

**Comment by isedwards** [comment]
My understanding is:
- The large red close icon that is at the bottom of the main menu will stay, but it will be made "more friendly"
- The form's close button (top right) will close the entire application even if other Climsoft forms are currently open

I'm happy with this. It should be possible to achieve the second point by capturing the close event on the main menu's form and adding the close code there.

**Comment by smachua** [comment]
@isedwards and @mhabimana I have addressed those issues in #372 please review and test it.

**Comment by mhabimana** [comment]
@rdstern This is the new Close button. Let us know your view:
![image](https://user-images.githubusercontent.com/10340170/45551211-cf918c80-b835-11e8-883f-1a0eac50e3dc.png)

**Comment by rdstern** [comment]
Yes, that's less aggressive.  I prefer it.

**Comment by mhabimana** [comment]
@rdstern Thanks for your quick feedback.

**Comment by mhabimana** [comment]
@smachua @isedwards This issue can now be closed since it was addressed.
