### ISSUE TITLE
Entry Date and Time Field required in New Data Forms

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#371]
This Field is required in all the new Data Entry form created by AMI,this will enable the computation of  records entered by a particular user (very helpful in data monitoring). @smachua has got already  a line of code to do this task and it exists already in form agro1. 
![image](https://user-images.githubusercontent.com/10340170/45365744-e0e45a00-b5e5-11e8-9ac5-e48dfd1a4d2b.png)

![image](https://user-images.githubusercontent.com/10340170/45544536-3c9a2780-b820-11e8-9f37-69e9efecf241.png)

**Comment by mhabimana** [comment]
@smachua Thanks

**Comment by smachua** [comment]
@Patowhiz  and @maxwellfundi may add a code in the new forms to capture the current date and time for every record saved.

**Comment by mhabimana** [comment]
@smachua You had done one line of code for this purpose,is it possible to share this to easy the task and save time?

**Comment by mhabimana** [comment]
@smachua Thanks. @Patowhiz  or @maxwellfundi are you happy to work on this?

**Comment by mhabimana** [comment]
@Patowhiz Very good.

**Comment by Patowhiz** [comment]
@smachua in formAgro1 , why are you not updating the entryDateTime and Signature column? I get it why you could not be updating the entryDateTime , probably because it's a field meant to store the original date that the record was entered but for the signature I don't understand.

Should we implement this for both update and new records, or strictly new records?

**Comment by Patowhiz** [comment]
@mhabimana it seems like @smachua added this field recently. Running the script just updates the database. For me to actually implement this then I need the field updated in the Entity Framework model. Perhaps @isedwards can help with this, after which I can go ahead and add the necessary single line of code

> @mhabimana I have made a script to add that field in those key entry tables that may not have it. See attachment.
> [key_entry_forms_add_entryDateime.txt](https://github.com/opencdms/Climsoft/files/2388338/key_entry_forms_add_entryDateime.txt)

**Comment by Patowhiz** [comment]
@smachua okay. Mu next pull request will rectify it. Because we had assumed that CLIMSOFT is to update the signature doing the changes regardless of whether he is updating or entering new record. From your statement above, I'll change this and have the signature column updated ONLY when it's a new record.

**Comment by mhabimana** [comment]
@smachua Below is the error I am getting:
![image](https://user-images.githubusercontent.com/10340170/45756058-9b98db80-bc28-11e8-895d-edab2b818dbb.png)

**Comment by smachua** [comment]
@mhabimana the issue has been resolved through PR #386

**Comment by mhabimana** [comment]
@smachua  This is now working OK. However,It is working on only 2 data entry forms(form_synop_2_ra1 and form_agro1). Can you please investigate why it is not applied to other forms before this issue is closed.

**Comment by mhabimana** [comment]
This can now be closed

**Comment by Patowhiz** [comment]
@mhabimana @smachua @isedwards  I have a noticed a potential bug with the entryDateTime field. The format saved by the entity framework is probably different from the one saved by raw sql insert operation. This makes the entry forms fail to load such records, throwing error _"wrong input format"_ . @mhabimana we can skype if need be to elaborate more, probably @smachua is aware of this.

**Comment by mhabimana** [comment]
@Patowhiz Thanks, I am travelling to Rwanda, @smachua will be able to advise on this.However the entry datetime datatype field was changed from VARCHAR to Datetime. In the EF, so I am suggesting that @smachua share a script with the new change .

**Comment by Patowhiz** [comment]
@smachua okay
