### ISSUE TITLE
Metadata 

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#376]
1.Station Tab:
The navigation order for the sub dialog Degrees Decimal conversion need few changes ,the same sub dialog is not clearing when **save** or **update** button is pressed, the Elevation label need few edit(value in the bracket);
2.Station Element Tab: Check why values entered under Instrument ID and Schedule Class drop down text boxes are being duplicated;
![image](https://user-images.githubusercontent.com/10340170/45608215-52932c80-ba5a-11e8-8c9b-e878fc2e9a00.png)

3.Station Location History: Check why Daily,Hourly,Monthly and AWS are appearing in the list of sationId as shown below:
![image](https://user-images.githubusercontent.com/10340170/45607811-891b7800-ba57-11e8-8ebe-31869d361d11.png)

**Comment by mhabimana** [comment]
@smachua @isedwards this is almost done, only awaiting few improvement suggested on clearing the sub dialog for Degrees lat/lon conversion into Degrees Decimal when save or update is button is clicked

**Comment by smachua** [comment]
@mhabimana solved through #380 .

**Comment by mhabimana** [comment]
@smachua This is working well and can now be closed.
