### ISSUE TITLE
Sequencer Form Hourly wind

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#384]
@Patowhiz  Can you please check why the sequencer (seq_month_day) for this form is not working when Add New is clicked? I can see the table for this sequencer is there in the database. Normarly,when AddNew is clicked I should have a empty form pointing to the next day.

**Comment by Patowhiz** [comment]
@mhabimana do you have records in the `seq_month_day` database table?

**Comment by mhabimana** [comment]
@Patowhiz yes,see below:
![image](https://user-images.githubusercontent.com/10340170/45760063-eb2fd500-bc31-11e8-93d1-e8624245b670.png)

**Comment by Patowhiz** [comment]
It's working on my side. Can I quickly get in touch with you on skype.

**Comment by mhabimana** [comment]
@Patowhiz Yes,please

**Comment by mhabimana** [comment]
@Patowhiz ,Yes,I can see the issue is on my database because I loaded the test shared by @smachua  today and this sequencer is working( going to the next day when Add **New button** is clicked.

**Comment by mhabimana** [comment]
@Patowhiz I think it is not a big issue,what is needed is just to check properly both database and make sure the tables are the same in both.

**Comment by mhabimana** [comment]
This can now be closed.

**Comment by mhabimana** [comment]
@Patowhiz @smachua Now I discover the issue on this form it is linked to the **permission** and not on the database. I think the user with the role **operator** does not have access to the sequencer table and because of this,when Add New is clicked,the sequencer table is not affected(or pointing to the next record).

**Comment by smachua** [comment]
@mhabimana I thought you closed the issue. However, I have addressed the issue of SELECT permission for table seq_month_day through PR #385. Merge it and the issue will be over.

**Comment by mhabimana** [comment]
This can now be closed.
