### ISSUE TITLE
Tab order on both Form Daily2 and Monthly

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#387]
@Patowhiz  Can you please have a look on the two forms(form Daily2 and Form Monthly) and adjust accordingly? after entering data and click on save,the next form to be selected automatically is **Add New** this is working well on other forms but not on the above 2 mentioned. @Patowhiz this is very urgent since we are going to install the software in Rwanda on Monday.

**Comment by Patowhiz** [comment]
Yep I'll have a look at this.

**Comment by mhabimana** [comment]
@Patowhiz  Thanks. well noted.

**Comment by Patowhiz** [comment]
@mhabimana I'm looking at this now.

**Comment by Patowhiz** [comment]
I have fixed this.

**Comment by Patowhiz** [comment]
@smachua @mhabimana this is ready for review
