### ISSUE TITLE
Form Daily 2 Sequencer does not move to the next month

### ISSUE THREAD

**Issue by maxwellfundi** [opencdms/Climsoft#391]
We have now upgraded the Climsoft V4 in Rwanda and we have found out that the sequencer for form daily two, after going through the all elements then i doesnt increment the month value.

**Comment by mhabimana** [comment]
@maxwellfundi.Thanks on the same note form monthly sequencer is not increment to the next year after going through all the elements;@pathowhiz can you have a look on this?

**Comment by Patowhiz** [comment]
I'm looking at both the issues now

**Comment by mhabimana** [comment]
@Patowhiz:Thanks,Noted.

**Comment by Patowhiz** [comment]
@dannyparsons we have to look at how we can implement the sorting or the sequencer as soon as possible. I've noticed various critical issues which have to be solved first for this to work.

**Comment by mhabimana** [comment]
https://github.com/dannyparsons,https://github.com/Pathowhiz: ca we have this fixed before we leave Kigali?

**Comment by mhabimana** [comment]
@Patowhiz,@dannyparsons: Can we have this fixed before we leave Kigali next week?

**Comment by Patowhiz** [comment]
@mhabimana this was particular feature was conceptualized by @dannyparsons and David. I have tagged and mentioned it to him too. Working on it will mean I probably redo it in different way, I've done very little modifications but upon investigating the problem I realised it's much deeper to solve without discussing with them first. My investigation led me to believe if the sequencer was to work correctly the way it is currently implemented, then we will have to sort the records when loading them. The way to sort them, and the columns to use in sorting is what I wasn't sure if it will be a generally good conceptualization in regard to the current implementation.

**Comment by Patowhiz** [comment]
Though I can work on it the way I think it will solve the issue then I'll discuss with danny to see if the implementation is generally acceptable. Probably by tomorrow I can have this ready

**Comment by mhabimana** [comment]
@Patowhiz:Noted.What we would like to see is to have the sequencer increment to the next month after running through all the elements (form Daily) and to the next year after running through all the elements(form Month).

**Comment by mhabimana** [comment]
@Patowhiz, @dannyparsons: The issue of loading speed is out but we still have the issue of the Add New button on both Hourly,Daily and Monthly once selected  is not giving an empty data entry form. Can you have a look at this so that this be implement tomorrow before we close the workshop? I am afraid if this is not working we might not implement the new data entry form designed by the AMI.

**Comment by Patowhiz** [comment]
I'm not getting this problem on my side. Can we Skype call (urgently). I tested this thoroughly
