### ISSUE TITLE
New data entry forms are taking too long to load

### ISSUE THREAD

**Issue by maxwellfundi** [opencdms/Climsoft#392]
We tried opening the new data entry forms after installation of Climsoft and here are some statistics of how the forms performed on their first load.

1. It took 2 minutes to load form daily 2 which had records 4648 records

2. It also took 7 minutes 40 seconds to load form hourly which had 28648 records 

We were using  an i7 with 8GB of memory and a 3,4 GHZ speed.After this slow loading the forms work okay. 

On the consecutive opening of these forms in the same instance, they loaded almost  instantly but every time a new climsoft session is run then it takes the same time to load.   

This time is too much to wait for the form to load and this needs to be addressed to make the forms more efficient in load time.

**Comment by mhabimana** [comment]
@isedwards : we are suspecting this low speed performance might be caused by the EF.Will it be possible to have a fix of this before we leave Kigali?

**Comment by Patowhiz** [comment]
I concur that's too long to wait. But the fact that the form loads instantaneously on the second run of the same sessions means that this has a lot to do with the EF taking time to compile the model on the first query. I think generating pre-compiled version of the EF could reduce the load time on first run significantly.

**Comment by dannyparsons** [comment]
I've had a quick discussion with David on this and we have an idea of where the inefficiency might be and something we can try to reduce the loading time. We will investigate this today and tomorrow and report back.
