### ISSUE TITLE
AWS Site settings form require a search bar. 

### ISSUE THREAD

**Issue by maxwellfundi** [opencdms/Climsoft#394]
This form needs a search bar because when trying to find a site from what is on the database then they have to use the scroll bar to move from 1st record to the last. This is easy when we have 10 sites but could be tiring if we had say 200 sites. 

Further the data structure field on this form needs to be longer .

![image](https://user-images.githubusercontent.com/9798689/46128713-ad840b00-c234-11e8-84ff-4a87eb7696e2.png)

**Comment by smachua** [comment]
@maxwellfundi the issue was resolved through PR #393

**Comment by maxwellfundi** [comment]
@smachua  great thanks. Closing it now.
