### ISSUE TITLE
Tab Key Order on Monthly Data Entry Form

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#403]
@Patowhiz The order of tab key on the Monthly data entry form need a slight change.Currently the order is from **Station** to the **first data entry box cell which is January** and yet it should be from  Station,then Element,then Year, then January. Are you happy to work on this?
![image](https://user-images.githubusercontent.com/10340170/47076694-fada1380-d207-11e8-91c3-5a0f6a8d56c4.png)

**Comment by mhabimana** [comment]
@Patowhiz : I have not yet heard from you on this.Are you happy to fix this?

**Comment by rdstern** [comment]
It is good that you keep following up on the issues.  But I use this example to ask also what is the current plan now to be on updates for CLIMSOFT?  You have 95 issues open now.  In R-Instat we have 524!  I assume, this is an example which isn't critical.  In R-Instat we have milestones to indicate when we consider issues need to be fixed by.  Will there be the same for CLIMSOFT?  That could indicate the priority attached to this and other issues.

**Comment by Patowhiz** [comment]
@maxwellfundi Could you please just realign the tab order at the design level. I have a high resolution PC that keeps on messing up the design. @mhabimana Sorry I don't how this tab order skipped us. Its just a design issue we already have the code built in.

**Comment by mhabimana** [comment]
@Patowhiz Thanks and noted.

**Comment by mhabimana** [comment]
@Patowhiz @maxwellfundi I realise that the tab order is applied on both Form Daily and Monthly when the form has  got some input records but when there is no record of data into this it jump from Station to the value text box1 . So I suggest we leave it like this at the moment.

**Comment by Patowhiz** [comment]
Okay. Then this can now be closed I think

**Comment by mhabimana** [comment]
@Patowhiz @maxwellfundi I reopen this issue again due to the feedback received from users from Rwanda.
The issue here is that if the cursor is on the station test box drop down list, and the Tab Key or Enter Key is pressed ,the cursor  jump from station to the text box of the first date on the Month for the form Daily and to the first month of the year for the form Monthly instead of going to the element drop down list box (When there are existing data in the form,the order is OK)  but the major issue  is when the user switch to another station in the drop down list, the tab order jump again from station to the text box of the first date on the Month for the form Daily and to the first month of the year for the form Monthly.
Can you please revisit this, I am available for further details.

**Comment by Patowhiz** [comment]
I've investigated this issue. There was a difference in adaptation of my code to the 2 forms, formDaily2 and formMonthlyData. That variation led to this problem but I've now corrected the code.

**Comment by isedwards** [comment]
As a software engineer, sometimes you see something in the code that feels like a [code smell](https://en.wikipedia.org/wiki/Code_smell) (something that doesn't quite "smell right").

A code smell is defined as:
> any characteristic in the source code of a program that possibly indicates a deeper problem.

One of the most [common code smells](https://en.wikipedia.org/wiki/Code_smell#Common_code_smells) is "[duplicated code](https://en.wikipedia.org/wiki/Duplicate_code)" - this is code that is repeated in a very similar way in multiple places and can result in errors being introduced when you are trying to keep multiple similar copies up-to-date in different places whenever something changes or needs fixing.

The solution is through [code refactoring](https://en.wikipedia.org/wiki/Code_refactoring):

> restructuring existing computer code—changing the factoring—without changing its external behavior.

In this case the aim would be to try to take the code that is repeated within the forms and write it as a single function or method that only exists is one place (and then only needs to be updated in a single place in the future).

This principal (also known as [don't repeat yourself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)) is one of the main aims behind the use of reusable user controls.

**Comment by isedwards** [comment]
I've added the comment above to the [Climsoft wiki](https://github.com/opencdms/Climsoft/wiki) as part of the developer's guide.  Another example of repeated code is in #369.

**Comment by Patowhiz** [comment]
Thanks for the observation @isedwards , I've been looking forward to remove such repetitions. I'm still waiting to discuss with the team about this and many more designs and implementations.

**Comment by isedwards** [comment]
The main guideline to-date has been to prioritise writing code that works (even if some of the code is repeated in places) because it has taken awhile to get version 4 ready.  I think it is always difficult to balance how much time is spent writing "perfect code" (if there is such a thing), against getting something that is clearing working correctly sent out to users as quickly as possible.
