### ISSUE TITLE
Form Monthly Issue

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#406]
@smachua @Patowhiz : I realise that on the form Monthly,values for January(mm_01) are not being saved in the form Monthly table after clicking on the save button,other months are being saved.However if the same text box is filled later and the update button is clicked,this value become available in this table,please check this:
![image](https://user-images.githubusercontent.com/10340170/47506573-087f4100-d879-11e8-956c-4006ed706d1b.png)

**Comment by Patowhiz** [comment]
I'm looking at this.

**Comment by mhabimana** [comment]
@Patowhiz Thanks,Noted.

**Comment by Patowhiz** [comment]
@mhabimana I'm not getting this issue from my end. On first save, I'm able to successfully view the value.

**Comment by mhabimana** [comment]
@Patowhiz Thanks,Have you selected the form Monthly View Button to view data in the table view?

**Comment by Patowhiz** [comment]
@mhabimana I still can't get a particular way to get this error. If you can be able to find a specific way to replicate this error then it would help. Upto now I'm unable to solve this cause I have not managed to replicate the error on my side.

**Comment by mhabimana** [comment]
@Patowhiz : I am testing this after merging with the latest PR. I will come back to you shortly.

**Comment by mhabimana** [comment]
@Patowhiz: After sorting out the issue of Tab order on this form,I can see this is now working well.

**Comment by Patowhiz** [comment]
There was a critical change that I made on the navigation control, it was mainly affecting deleting of records. I think that change might have also solved this but. I'll keep an eye on this sort of behaviour.

**Comment by mhabimana** [comment]
@Patowhiz : Thanks,Well done. I think this can now be closed.

**Comment by isedwards** [comment]
@mhabimana in the original description above it sounded like this was possible data loss issue.

Do we know whether users of the deployed version 4.1 are being affected by this issue (have @Patowhiz's changes fixed a data loss issue since the 4.1 version was released?)

**Comment by mhabimana** [comment]
@isedwards  : Thanks, Of course ,this bug is in the V4.1 released. Since this Form is not used frequently by NMSs,it is not a problem but we need to upgrade the executable files of users who are already using V4.1 and then,have a new installer with the latest changes on GitHub. I had a Skype meeting and managed to share my screen with @Patowhiz  and he was able to see the issue on this form clearly.

**Comment by mhabimana** [comment]
@isedwards : I leave this issue now for further investigation but it is working well on my side.

**Comment by isedwards** [comment]
Next steps...
a) make sure it really is an issue (it's best that someone else checkout/install v4.1 and try to duplicate the problem)
b) Be certain of the minimal code required to fix just this issue
c) Release a bug fix (v4.1.1). In this case the release may only address a single issue, but if it is a data loss issue then that is normal

**Comment by mhabimana** [comment]
This can now be closed.
