### ISSUE TITLE
5 year roadmap (plus milestones and project planning)

### ISSUE THREAD

**Issue by isedwards** [opencdms/Climsoft#408]
This [comment](https://github.com/opencdms/Climsoft/issues/403#issuecomment-432117080) from @rdstern accidentally disappeared when #403 was closed.

> It is good that you keep following up on the issues. But I use this example to ask also what is the current plan now to be on updates for CLIMSOFT? You have 95 issues open now. In R-Instat we have 524! I assume, this is an example which isn't critical. In R-Instat we have milestones to indicate when we consider issues need to be fixed by. Will there be the same for CLIMSOFT? That could indicate the priority attached to this and other issues.

Over the next couple of weeks we need to:
- Update the Climsoft [Roadmap](https://github.com/opencdms/Climsoft/wiki/Climsoft-Roadmap)
- Assign issues to milestones
- Update [Project boards](https://github.com/opencdms/Climsoft/projects)

**Comment by isedwards** [comment]
The tasks in this issue is being addressed during the Kitale workshop and therefore will be completed before the v4.1.4 release.

**Comment by Patowhiz** [comment]
@iedwards please note I'm still waiting for the road map of  version 5 to help update the milestones for the issues raised accordingly. In the meantime I'll only update for version 4 since its the only one available.

**Comment by Patowhiz** [comment]
@iedwards @dannyparsons @smachua @mhabimana we need to know the due date for 4.1.4 milestone (March Sprint), So that the team can know about its deadline. 

@smachua @maxwellfundi is it viable to have this milestone achieved before the Malawi installation?

**Comment by isedwards** [comment]
@Patowhiz I will email you the current draft roadmap.  I expect it to be completed this week and put online for everyone to comment.

We should make sure each version is well tested before release.

**Comment by isedwards** [comment]
The Climsoft 5 year road map, discussed in Kitale, is now available here:
    https://github.com/opencdms/Climsoft/wiki/Climsoft-Roadmap

Please let me know any changes that are needed by commenting on this issue.

If there are no major changes then I intend to mark the road map as "adopted" next Friday (5th April 2019)

**Comment by mhabimana** [comment]
@isedwards : Looks great. I have edited few typing errors ,but  the last scale  for the release cycle need correction as well from thirty party to third-party.
