### ISSUE TITLE
Immediate use of daily data in CLIMSOFT

### ISSUE THREAD

**Issue by rdstern** [opencdms/Climsoft#416]
In Lesotho currently the Ag Met section receive daily (rainfall) data each week.  This is entered into Excel and used fro the AgroMet bulletins.  That is separate from the past system in CLIMSOFT, which enters the same data from the monthly sheets usually about 3 months later.

In CLIMSOFT 4.1 they would like to enter the daily data straight into CLIMSOFT as it arrives each week.  Then export it for the AgroMet bulletins.  Of course the current daily data sheet isn't ideal, because they don't then have the monthly totals.  

How should they do this?  I remember that KMD had the same problem a few years ago and I think that is now solved with the version of CLIMSOFT used in Kenya.  So I guess there is a simple solution with CLIMSOFT 4.1?

**Comment by smachua** [comment]
The form, 'Kenya Agromet data' can be used for that purpose. Although it contains all the daily elements those not required can be skipped.

**Comment by mhabimana** [comment]
@rdstern The same daily form can be used but in this case,the required total in metadata,element tab is untick to make sure the total is not checked by the system.So after a week,values for the week can be entered and **saved**(here I mean using the Save button),after the next week,values for the second week are entered and **updated**(here I mean using the update button).Hope it makes sense.

**Comment by Patowhiz** [comment]
I'm closing this issue, it has already been addressed in the current version of CLIMSOFT. It's just about how the metadata for the element is set.
