### ISSUE TITLE
Importing Clicom Daily Data

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#418]
@smachua: There is a problem of speed of transfer of CLICOM Daily data into Climsoft Version4. This is being done using the schema.ini techniques. I wonder if another method which speed up this process can be explored or the issue of data transfer speed be addressed. This issue was raised as point (2) in the issue #366 among other points INAM-Mozambique would wish to get fixed before the adoption and implementation of Climsoft V4 as their operation CDMS. They have been using CLICOM in the past and  their historical data are still in CLICOM. Another issue is that if you continue to do other tasks on your PC while transfering these data,the data transfer progress bar hangs and you cannot be able to see the progress though the process continue in the background (see below).
![image](https://user-images.githubusercontent.com/10340170/48255891-08597680-e41f-11e8-8a51-3006f9afef63.png)

**Comment by rdstern** [comment]
If we are going to consider installing CLIMSOFT plus R-Instat, then another possible route might be to export the data from CLIMSOFT, and then to start by examining it first in R-Instat.  Then going from R-Instat to CLIMSOFT.  Is there another visit to Mozambique to "sell" the set of 2 packages.  If not, then should there be?
The 2 exports are then 1) by element which gives values from days 1 to 31 in one record, or 2) by observation.  Both go easily into R-Instat.  Then we could export the data into CLIMSOFT after perhaps looking at a bit of the QC etc in R-Instat.

How is the transfer of the station information from CLICOM to CLIMSOFT?  Is that easy?

**Comment by smachua** [comment]
@mhabimana @rdstern the issue has now been resolved thro #430. CLICOM import module was modified to use the same dialog as all other external text data imports. The data transfer speed has tremendously improved.  All the CLICOM data formats namely Daily, Synop and Hourly are now accommodated as shown below;

![image](https://user-images.githubusercontent.com/12034121/49889067-a8a51f80-fe51-11e8-9000-be29a7ace0c2.png)

**Comment by mhabimana** [comment]
@smachua 👍
