### ISSUE TITLE
Error loading the solution file in VS

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#431]
I am getting this error after merging the latest PR on Clicom pushed by @smachua ,Thought I can still login into Climsoft, how can I resolve this? 
![image](https://user-images.githubusercontent.com/10340170/49938073-c7ef8b80-fee9-11e8-8e09-110f5531a7b9.png)

**Comment by smachua** [comment]
@mhabimana it might be something to do with the project in your machine. I have cloned it and didn't encounter the message. Try rebuilding the executable file first then see how it works. To do that; from the project window follow the menu **_Build_** -> **_Rebuild ClimsoftVer4_**.

**Comment by mhabimana** [comment]
@smachua Thanks,let me try this option and come back to you.

**Comment by mhabimana** [comment]
@smachua Now I am OK,my MAT was disabled. I have enabled this and now I am not seing the error.
