### ISSUE TITLE
Missing corresponding field in database for the metadata physical feature form 

### ISSUE THREAD

**Issue by maxwellfundi** [opencdms/Climsoft#434]
The feature class control on the metadata physical feature tab does not have a corresponding field in the `physicalfeature` table in the database.

![image](https://user-images.githubusercontent.com/9798689/50886550-c7bbb080-1401-11e9-8e0b-f6033729ade7.png)

@smachua what should this corresponding field to this? Should this be added to the table or remove it from the form?

**Comment by smachua** [comment]
I will respond to this issue later because am a bit tied down with the work on online help to harmonise it with the  help document. That form involves more than one table but we shall discuss later since what am currently doing has a higher priority and with a deadline.

**Comment by Patowhiz** [comment]
@smachua in the meantime that input field has been omitted. We can have it back once that is discussed.
@mhabimana from your screenshot above, you can see there is no Clear nor Cancel button like in the data entry version. So currently when a user clicks on Add New, He/She has to click on the navigation button if He/She desires to cancel the add new. 
@smachua  @mhabimana Should we introduce the Clear/Cancel button for this?

**Comment by mhabimana** [comment]
@Patowhiz .You are right,Clear and Cancel buttons are not on the dialog. It is a good idea to include these buttons on the dialog.

**Comment by mhabimana** [comment]
@Patowhiz I think Clear and Cancel are totally different. In Climsoft we normally use Clear to clear the content of the form at input the content a fresh and Cancel to cancel or close the dialog.

**Comment by maxwellfundi** [comment]
@Patowhiz  I am also happy with `Clear` for this case because `Cancel ` intuitively would be like closing the form which is something we dont want for this case. Clear serves the purpose here because its meant to clear the contents of  the fields.

**Comment by mhabimana** [comment]
@Patowhiz Thanks,yes please.It make sense.

**Comment by smachua** [comment]
@Patowhiz there is no field that's missing. If you run the form and save some data you will find that the boxes get populated when the record is retrieved. See the screenshot by @mhabimana above.

**Comment by Patowhiz** [comment]
@smachua clearly @mhabimana screenshot shows 7 input controls, the database table has 6 fields, the screenshot also shows that class description is empty. Please elaborate how the 7 input controls are mapped to the 6 fields. I've tried looking at you code, I can't find where the Class Description(`txtFeatureClassDescription`) is mapped to a field named description in the database table, which is already mapped to  Feature Class (`txtFeatureDescription` ). Probably I'm missing something. Below is your save code.

```
 Private Sub cmdAddFeature_Click(sender As Object, e As EventArgs) Handles cmdAddFeature.Click

        Try
            ' Update Feature Class
            ' Set the feature Class definition
            SetDataSet("physicalfeatureclass")
            Dim cb As New MySql.Data.MySqlClient.MySqlCommandBuilder(da)
            Dim dsNewRow As DataRow
            Dim recCommit As New dataEntryGlobalRoutines
            dsNewRow = ds.Tables("physicalfeatureclass").NewRow

            dsNewRow.Item("featureClass") = txtFeatureClass.Text
            dsNewRow.Item("refersTo") = txtFeatureStation.Text
            dsNewRow.Item("description") = txtFeatureClassDescription.Text

            ds.Tables("physicalfeatureclass").Rows.Add(dsNewRow)
            da.Update(ds, "physicalfeatureclass")

            ' Update Physical Feature
            ' Set the feature Class definition
            SetDataSet("physicalfeature")
            Dim cp As New MySql.Data.MySqlClient.MySqlCommandBuilder(da)
            Dim dsNewRowp As DataRow
            Dim recCommitp As New dataEntryGlobalRoutines

            dsNewRowp = ds.Tables("physicalfeature").NewRow

            dsNewRowp.Item("associatedWith") = txtFeatureStation.Text
            dsNewRowp.Item("beginDate") = txtFeaturedBdate.Text
            dsNewRowp.Item("endDate") = txtFeaturedEdate.Text
            dsNewRowp.Item("image") = txtImageFile.Text
            dsNewRowp.Item("description") = txtFeatureDescription.Text
            dsNewRowp.Item("classifiedInto") = txtFeatureClass.Text

            'Add a new record to the data source table
            ds.Tables("physicalfeature").Rows.Add(dsNewRowp)
            da.Update(ds, "physicalfeature")

            ClearPhysicalFeatureForm()

        Catch ex As Exception
            If ex.HResult = 5 Then
                MsgBox("Invalid Entries; Check values")
            Else
                MsgBox(ex.Message)
            End If
        End Try
    End Sub
```

From my understanding of your code, I'm I correct to say that 2 input controls are mapped to the same field and that we can remove one of the controls?

**Comment by mhabimana** [comment]
This can be closed.
