### ISSUE TITLE
Station search by name

### ISSUE THREAD

**Issue by plamptey** [opencdms/Climsoft#447]
I am new to Climsoft and from the Ghana Met. Agency.
I wish i could search station by name by just typing a few letters of the station name. 
I have been able to import the station information into the climsoft database. However when i wish to be able to search the station by name by just typing a few letters of the station name in the ''Search Station Name'' dialogue box.

**Comment by mhabimana** [comment]
@plamptey :Thanks for raising this issue.However,which dialog do you mean,Can you share with us the screenshot? because,the search option on the metadata information is working very well(see below):
![image](https://user-images.githubusercontent.com/10340170/52408696-7aa42a80-2ae4-11e9-93d6-f214cd885e18.png)

**Comment by rdstern** [comment]
This is a good issue to raise.  My understanding would be that what is wanted by Lamptey is that the only stations listed in the example above would be those with "kig" in the name.  In the instance above you have jumped to (presumably) the first instance of "kig", but then all the following stations are listed.

I assume the custom controls could be used to provide different options here, and perhaps this is already the case for the data entry dialogues.  It is a perhaps a good example for @maxwellfundi and @Patowhiz to respond also.

**Comment by isedwards** [comment]
Also, in the example Marcellin showed, the stations are not ordered alphabetically, so it is still difficult to find the station that you need.

There's actually already an issue open to improve the search options, hopefully this will help: https://github.com/opencdms/Climsoft/issues/446

**Comment by plamptey** [comment]
> @plamptey :Thanks for raising this issue.However,which dialog do you mean?,Can you share with us the screenshot? because,the search option on the metadata information is working very well(see below):
> ![image](https://user-images.githubusercontent.com/10340170/52408696-7aa42a80-2ae4-11e9-93d6-f214cd885e18.png)
Hi @mhabimana thank you for the prompt response and the screenshot. I have actually realized my mistake; i was pressing the 'enter' key to get the list of stations but i realized by clicking on the drop down it list the stations in the order starting with the initial letters i keyed in.
Thank you all for your response!!

**Comment by Patowhiz** [comment]
With the custom controls this type of searching has been improved much further, for instance a pop of the stations with the typed letters will be shown and extra features like autocomplete.
