### ISSUE TITLE
form_hourlywind - Data Entry Form For Hourly Wind Data

### ISSUE THREAD

**Issue by Patowhiz** [opencdms/Climsoft#498]

**Comment by Patowhiz** [comment]
@mhabimana @smachua in the the current database that I have, the table for hourlywind doesn't have the flag columns, were these intentionally removed? They were there previously

**Comment by mhabimana** [comment]
@Patowhiz:Thanks,Flags columns should be there, 23 columns see attached script.
[form_hourlywind.txt](https://github.com/opencdms/Climsoft/files/3405044/form_hourlywind.txt)

**Comment by isedwards** [comment]
@Patowhiz - copies of the database creation scripts are always available in [`https://github.com/opencdms/climsoft-database`](https://github.com/opencdms/climsoft-database).

Old versions of the script can also be downloaded from the [releases](https://github.com/opencdms/climsoft-database/releases) section.
