### ISSUE TITLE
Updating station metadata after import 

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#516]
This error message occurs when trying to update station metadata information  after importing these. The truc to avoid this error is to logout into Climsoft after the import and then login again and perform any required update on the station metadata. So,this is a bug which need to be addressed; User should be able to edit the metadata information after importing these and should not need to logout and login again to be able to perform any modification or updat on the metadata. 
![image](https://user-images.githubusercontent.com/10340170/56210376-60477980-605e-11e9-9f52-1d4033085cdb.png)

**Comment by mwaurahk** [comment]
Hi all,
The station search in Metadata management is very slow and takes ages to display stations already in the database..I have about 3117 stations in the database..Climsoft v4.13 runs on the server and will crash or become unresponsive when I do a station search in Metadata Management.

**Comment by mwaurahk** [comment]
![image](https://user-images.githubusercontent.com/20796608/56343272-ef6da200-61c2-11e9-9435-f0adf2ae9166.png)
