### ISSUE TITLE
Flag

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#547]
Below letters are commonly used as flag in Climsoft and we should not allow other letters to sail in the system as it is now. @Patowhiz can you restrict the forms to allow only these letters and not all letters as it is the case now in the flag?
Flag letters define in Climsoft:
**M** (Missing), the data value is missing;
**T** (Trace), the data value has been recorded as zero but a small trace was observed;
**E** (Estimated), the data value is an estimated value rather than an observed value.
**G** (Generated), the data has been generated from other values.
**D** (Dubious), Dubious or suspect value (data).

**Comment by mhabimana** [comment]
Below letters are commonly used as flag in Climsoft and we should not allow other letters to sail in the system as it is now. @patowhiz can you restrict the forms to allow only these letters and not all letters as it is the case now?
Flag letters define in Climsoft: 
**M** (Missing), the data value is missing;
**T** (Trace), the data value has been recorded as zero but a small trace was observed;                                                           
**E** (Estimated), the data value is an estimated value rather than an observed value.
**G** (Generated), the data has been generated from other values. 
**D** (Dubious), Dubious or suspect value (data).

**Comment by Patowhiz** [comment]
Yes I can

**Comment by Patowhiz** [comment]
I'm implementing this at the uctTextBox level, which will make any custom textbox be able to validate the flags. I'm hard coding the flags in the application for now but this can be enhanced to read the possible flag values from the database later.

**Comment by Patowhiz** [comment]
@mhabimana did you test this particular feature? Is it working as expected?

**Comment by mhabimana** [comment]
@Patowhiz -Thanks, It is not working as expected because,it is accepting other letters and yet it **should accept only** mentioned letters defined in the flag table below .
Flag letters define in Climsoft:
M (Missing), the data value is missing;
T (Trace), the data value has been recorded as zero but a small trace was observed;
E (Estimated), the data value is an estimated value rather than an observed value.
G (Generated), the data has been generated from other values.
D (Dubious), Dubious or suspect value (data).
![image](https://user-images.githubusercontent.com/10340170/63595948-d5096200-c5c2-11e9-95fd-a268acc9aa28.png)

**Comment by Patowhiz** [comment]
I probably missed something during the merging. I'll create a new PR to solve this.

**Comment by Patowhiz** [comment]
@mhabimana I think we are running different kind of versions. I merged my master with the current open cdms master changes. And the unKnown flags are not allowed by the control.

Can you please check that you have the latest changes merged.

![latest form](https://user-images.githubusercontent.com/21179007/63843367-f8e7f180-c98e-11e9-9dc7-241a4cc5f98f.JPG)

**Comment by mhabimana** [comment]
@Patowhiz : Thanks,Yes,I can see.I have the latest version of the master and will give you my feedback soon.

**Comment by mhabimana** [comment]
@Patowhiz : Thanks-This is now working well and can now be closed.
