### ISSUE TITLE
Improve the Data Key Entry Forms Dialog

### ISSUE THREAD

**Issue by Patowhiz** [opencdms/Climsoft#549]
Currently the data key entry form that contains links to the key entry forms is using data grid control as a means to for the user to access the key entry forms. This form can be improved to use a much better control. This was mentioned as part of the April code sprint.

![key entry forms](https://user-images.githubusercontent.com/21179007/61641379-b2c0b380-aca7-11e9-902a-e969c9e3f398.PNG)

**Comment by mhabimana** [comment]
@Patowhiz - Yes,this was mentioned in Kitale. Good if you can come up with an alternative option. We will then discuss,compare and select the best option.

**Comment by Patowhiz** [comment]
@smachua you changed control used in formDataForms from grid to listview? I was not aware of this change and the issue related to it

**Comment by smachua** [comment]
@Patowhiz it has always been a listview. May be you have never opened it before.

**Comment by berenger07** [comment]
Bonjour,

j'utilise ClimSoft depuis peut et j'aimerais recevoir une aide pour créer et personnaliser des formulaires. En effet on souhaiterait sur ClimSoft disposer de formulaires correspondant aux carnets d'observations de nos stations synoptiques. 
De plus j'aimerais aussi pouvoir créer dans ces formulaires des champs calculés automatiquement en y insérant des formules pour calculer automatiquement des paramètres comme l'humidité, déterminer le minimum et le maximum d'une observation journalière une fois les données journalière saisie. Merci.

**Comment by mhabimana** [comment]
@berenge07- Merci bcp pour votre email. Il serait mieux d'utiliser les formulaires de saisie actuellement existant dans climsoft pour faire la saisie de vos données climatiques. Le carnet d'observation contient les données journalières et horaires et les formulaires pour saisir ces types de données existent déjà dans Climsoft. cordialement.

**Comment by berenger07** [comment]
Bonjour,
merci pour vos directives. 
J'ai fais comme vous avez dit et j'ai réussi à utiliser les formulaires journaliers et horaires déjà existant dans Climsoft pour entrer des données correspondant aux paramètres relevés dans les carnets d'observations. 
De plus j'ai ajouté des données historiques contenu dans des fichiers CSV à Climsoft en faisant correspondre les entêtes des colonnes dans le menu "data Transfert" de Climsoft. Cependant j'ai du mal à retrouver ces données importer dans Climsoft. Je vois bien que l'importation se fais mais je n'arrive plus à revoir les données importées comme lorsque je saisis directement à travers les formulaires (là je vois les données saisie en faisant View et je peux les exporter).
A noté que pour l'importation j'utilise  le menu "data transfert" la fenêtre "external data" et le mode "multiple element columns". Je paramètre comme spécifié dans les supports tutoriels. Mais lorsque je fais view pour afficher le contenu du fichier CSV il n'est pas complet. Il me montre que les données d'une journée (0h à 23h) pourtant le fichier contient les données d'un mois. 
Donc ma question ici est es ce que l'on peu importer des données de plusieurs jours, ou mois voir des années en une seul fois pour les stockés sur climsoft pour pouvoir les consulter plus tard ou faire des requêtes pour voir leur contenu directement sur Climsoft ?
Ensuite j'aimerais savoir s'il est possible de créer des formulaires avec des formules ? De sorte que lors des saisies des données horaires par exemple ils puissent automatiquement me données le résultat calculés. Cela pour les paramètres tel que l'ETp (évapotranspiration), la température moyenne, le TMAX, le TMIN ect.... 
En claire je saisie les données de température d'une journée (de 00h à 23h) et il me sors directement le TMAX, le TMIN et la Tmoy de la journée.
CordialementKOUACOU Adou Kouassi Doré BérengerSpécialiste en Télédétection, SIG et Bases de Données Direction de la météorologie Nationale (SODEXAM)Contact: +225 08736793/+22505655191Boîte Postale: 22 BP 801 Abidjan 22

 

    Le dimanche 31 janvier 2021, 12:43:00 UTC, Marcellin <notifications@github.com> a écrit :  
 
 


@berenge07- Merci bcp pour votre email. Il serait mieux d'utiliser les formulaires de saisie actuellement existant dans climsoft pour faire la saisie de vos données climatiques. Le carnet d'observation contient les données journalières et horaires et les formulaires pour saisir ces types de données existent déjà dans Climsoft. cordialement.

**Comment by mhabimana** [comment]
@berenger07 - Merci bcp de nous faire part de ton évolution. C’est gentil.
Concernant le transfert de données (importation) en utilisant le fichier de données, je te recommande à visiter le lien pour plus de détails pour visualiser les données après importation (vidéo démo) : vidéo sur le transfert des données horaire (English). 
Toutefois, pour répondre à ta question concernant l’importation: Climsoft importe tous les données contenant dans ce fichier sans limite (plusieurs jours, mois, années) mais le dialogue de transfert de données indique le premier 25 lignes de données seulement de ce fichier.
Concernant la création des formulaires avec des formules : je dirai qu’après avoir faire la saisie des données horaire en utilisant les formulaires de saisie Climsoft, l’étape suivant c’est le transfert de ces données dans le tableau observation initial ou se font le contrôle de qualité de données pour enfin transférée ces données dans le tableau observation final. Alors, les calculs (requetés et autres formules  pour générées les diffèrent produits (Maxi, Mini, Moyenne journalière, Mensuelle, Annuelle, etc.) se font en utilisant les données contenant dans ce tableau. 
Pour être plus claire, si par exemple vous avez saisi (en utilisant le formulaire de saisie horaire Climsoft) les données horaires de température (00h à 23h), pour calculer le Maxi et mini journalière, il faut tout d’abord que ce données soit transférées dans le tableau observation initial, puis faire le CQ (Contrôle de Qualité) et puis transférée ensuite ces données dans le tableau observation final et puis générée le  Maximum et Minimum, Moyenne journalière, etc., en passant par l’icône de produit climatique (Climate Product-Data-Daily-Spécifier la période voulue) pour trouver le résultat.
