### ISSUE TITLE
QC for AWS Data

### ISSUE THREAD

**Issue by mublandy** [opencdms/Climsoft#553]
I am unable to QC AWS data being at the client PC , I am getting the error that the path is not right This operation is possible only on the server. Is it possible to set this operation to be done at the Client side since the server may be located in a different and inaccessible place?

**Comment by smachua** [comment]
@mublandy you can set the folder of your choice where the QC reports will be saved. From Welcome form follow;Tools -> General Settings.

**Comment by Iyakaremyevedaste** [comment]
Thanks @smachua . It works. What about backup at the local machine instead of using server?

**Comment by Patowhiz** [comment]
@mublandy did @smachua suggestion fix your issue?

**Comment by mhabimana** [comment]
@Patowhiz -This was fixed.The issue can now be closed.The issue was due to the QC folder  at the Client PC which was not set properly.
